{
 "title": "Network Health",
 "tags": [ "Platform" ],
 "time": { "from": "2024-02-09T17:50:36.987Z", "to": "2024-02-11T21:57:23.869Z" },
 "templating": {
  "list": [
   {
    "name": "network",
    "label": "Network",
    "query": {
     "query": "label_values(platform_trans_per_sec{network!~\"nmt.*\"},environment)"
    }
   },
   { "name": "NodeID", "label": "Node ID", "query": { "query": "label_values(node_id)" } }
  ]
 },
 "panels": [
  { "title": "Platform Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "gridPos": { "h": 19, "w": 22, "x": 0, "y": 1 } },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "healthyNetworkFraction",
   "type": "timeseries",
   "description": "The fraction (out of 1.0) of the network that is alive and healthy, weighted by consensus weight.",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "platform_healthyNetworkFraction_fraction{environment=\"$network\", type=\"mean\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  {
   "title": "Current healthyNetworkFraction",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 22, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(last_over_time(platform_healthyNetworkFraction_fraction{environment=\"$network\", node_id=~\"$NodeID\", type=\"mean\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "trans/sec",
   "type": "timeseries",
   "description": "The number of app transactions added to the hashgraph per second by each node via deduplicated events.",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "platform_trans_per_sec{environment=\"$network\", type=\"mean\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  {
   "title": "Avg trans/sec",
   "type": "stat",
   "description": "The average number of app transactions added to the hashgraph per second by the network via deduplicated events.",
   "gridPos": { "h": 8, "w": 2, "x": 22, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(platform_trans_per_sec{environment=\"$network\", type=\"mean\", node_id=~\"$NodeID\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "secC2C",
   "type": "timeseries",
   "description": "The time from creating an event to knowing its consensus (in seconds).",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "platform_secC2C{environment=\"$network\", type=\"mean\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{ node_id }}"
    }
   ]
  },
  {
   "title": "secC2C",
   "type": "stat",
   "description": "Of the secC2C values reported by each node, the minimum, average, and maximum.",
   "gridPos": { "h": 8, "w": 2, "x": 22, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(min_over_time(platform_secC2C{environment=\"$network\", type=\"min\", node_id=~\"$NodeID\"}[$__range]))",
     "legendFormat": "Min"
    },
    {
     "expr": "avg(platform_secC2C{environment=\"$network\", type=\"mean\", node_id=~\"$NodeID\"})",
     "legendFormat": "Avg"
    },
    {
     "expr": "max(max_over_time(platform_secC2C{environment=\"$network\", type=\"max\", node_id=~\"$NodeID\"}[$__range]))",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "cEvents/sec",
   "type": "timeseries",
   "description": "The number of events per second created by each node in the network.",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "platform_cEvents_per_sec{environment=\"$network\", type=\"mean\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  {
   "title": "cEvents/sec",
   "type": "stat",
   "description": "The average number of events per second created by each node.",
   "gridPos": { "h": 8, "w": 2, "x": 22, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(min_over_time(platform_cEvents_per_sec{environment=\"$network\", type=\"mean\", node_id=~\"$NodeID\"}[$__range]))",
     "legendFormat": "Min"
    },
    {
     "expr": "avg(platform_cEvents_per_sec{environment=\"$network\", type=\"mean\", node_id=~\"$NodeID\"})",
     "legendFormat": "Avg"
    },
    {
     "expr": "max(max_over_time(platform_cEvents_per_sec{environment=\"$network\", type=\"mean\", node_id=~\"$NodeID\"}[$__range]))",
     "legendFormat": "Max"
    }
   ]
  },
  { "gridPos": { "h": 8, "w": 16, "x": 0, "y": 53 } },
  { "gridPos": { "h": 8, "w": 8, "x": 16, "y": 53 } },
  { "gridPos": { "h": 8, "w": 22, "x": 0, "y": 61 } },
  {
   "title": "consEvents",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 22, "y": 61 },
   "targets": [
    {
     "expr": "min(min_over_time(internal_consEvents{environment=\"$network\", node_id=~\"$NodeID\"}[$__range]))",
     "legendFormat": "Min"
    },
    {
     "expr": "avg(internal_consEvents{environment=\"$network\", node_id=~\"$NodeID\"})",
     "legendFormat": "Avg"
    },
    {
     "expr": "max(max_over_time(internal_consEventsMAX{environment=\"$network\", node_id=~\"$NodeID\"}[$__range]))",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "secTransH",
   "type": "timeseries",
   "description": "The average time to handle a consensus transaction in SwirldState.handleTransaction()",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "internal_secTransH{environment=\"$network\", type=\"mean\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  {
   "title": "Network secTransH",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 22, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(min_over_time(internal_secTransH{environment=\"$network\", type=\"mean\", node_id=~\"$NodeID\"}[$__range]))",
     "legendFormat": "Min"
    },
    {
     "expr": "avg(internal_secTransH{environment=\"$network\", type=\"mean\", node_id=~\"$NodeID\"})",
     "legendFormat": "Avg"
    },
    {
     "expr": "max(max_over_time(internal_secTransH{environment=\"$network\", type=\"mean\", node_id=~\"$NodeID\"}[$__range]))",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "preHandleMicros",
   "type": "timeseries",
   "description": "The average time it takes to perform preHandle.",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "internal_preHandleMicros{environment=\"$network\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  {
   "title": "Network preHandleMicros",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 22, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(min_over_time(internal_preHandleMicros{environment=\"$network\", node_id=~\"$NodeID\"}[$__range]))",
     "legendFormat": "Min"
    },
    {
     "expr": "avg(internal_preHandleMicros{environment=\"$network\", node_id=~\"$NodeID\"})",
     "legendFormat": "Avg"
    },
    {
     "expr": "max(max_over_time(internal_preHandleMicros{environment=\"$network\", node_id=~\"$NodeID\"}[$__range]))",
     "legendFormat": "Max"
    }
   ]
  }
 ]
}