{
 "title": "Threads & Queues",
 "tags": [ "Platform" ],
 "time": { "from": "2024-02-09T17:50:36.987Z", "to": "2024-02-11T21:57:23.869Z" },
 "templating": {
  "list": [
   {
    "name": "network",
    "label": "Network",
    "query": {
     "query": "label_values(platform_trans_per_sec{environment!~\"nmt.*\"},environment)"
    }
   },
   { "name": "NodeID", "label": "Node ID", "query": { "query": "label_values(node_id)" } }
  ]
 },
 "panels": [
  { "gridPos": { "h": 16, "w": 16, "x": 0, "y": 0 } },
  { "title": "Pre Consensus Handling", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "preConsEvents",
   "type": "timeseries",
   "description": "The average number of events in the preconsensus queue (q1) waiting to be handled.",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "internal_preConsEvents{environment=\"$network\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  {
   "title": "preConsEvents",
   "type": "gauge",
   "description": "The average number of events in the preconsensus queue (q1) waiting to be handled.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(min_over_time(internal_preConsEvents{environment=\"$network\", node_id=~\"$NodeID\"}[$__range]))",
     "legendFormat": "Min"
    },
    {
     "expr": "avg(internal_preConsEvents{environment=\"$network\", node_id=~\"$NodeID\"})",
     "legendFormat": "Avg"
    },
    {
     "expr": "max(max_over_time(internal_preConsEvents{environment=\"$network\", node_id=~\"$NodeID\"}[$__range]))",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "preConsEvents Busy Fraction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "internal_thread_busy_thread_curr_fraction{environment=\"$network\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  {
   "title": "preConsEvents Busy Fraction",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "targets": [
    {
     "expr": "min(min_over_time(internal_thread_busy_thread_curr_fraction{environment=\"$network\", node_id=~\"$NodeID\"}[$__range]))",
     "legendFormat": "Min"
    },
    {
     "expr": "avg(internal_thread_busy_thread_curr_fraction{environment=\"$network\", node_id=~\"$NodeID\"})",
     "legendFormat": "Avg"
    },
    {
     "expr": "max(max_over_time(internal_thread_busy_thread_curr_fraction{environment=\"$network\", node_id=~\"$NodeID\"}[$__range]))",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Application transaction prehandler: unhandled task count",
   "type": "timeseries",
   "description": "The number of tasks waiting to be prehandled",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "platform_applicationTransactionPrehandler_unhandled_task_count{environment=\"$network\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  { "title": "Event Intake", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "intakeQueue Busy Fraction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "internal_thread_busy_event_intake_fraction{environment=\"$network\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  {
   "title": "intakeQueue Busy Fraction",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 42 },
   "targets": [
    {
     "expr": "min(min_over_time(internal_thread_busy_event_intake_fraction{environment=\"$network\", node_id=~\"$NodeID\"}[$__range]))",
     "legendFormat": "Min"
    },
    {
     "expr": "avg(internal_thread_busy_event_intake_fraction{environment=\"$network\", node_id=~\"$NodeID\"})",
     "legendFormat": "Avg"
    },
    {
     "expr": "max(max_over_time(internal_thread_busy_event_intake_fraction{environment=\"$network\", node_id=~\"$NodeID\"}[$__range]))",
     "legendFormat": "Max"
    }
   ]
  },
  { "gridPos": { "h": 8, "w": 16, "x": 0, "y": 50 } },
  { "gridPos": { "h": 8, "w": 8, "x": 16, "y": 50 } },
  {
   "title": "intakeQueue (post hash collector)",
   "type": "timeseries",
   "description": "The number of unhandled tasks waiting to enter the intake pipeline. Events accumulate waiting for intake in the post hash collector",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "platform_postHashCollector_unhandled_task_count{environment=\"$network\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  { "title": "Event Creator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "eventCreator Busy Fraction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 69 },
   "targets": [
    {
     "expr": "internal_thread_busy_event_creator_fraction{environment=\"$network\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  {
   "title": "eventCreator Busy Fraction",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 69 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(min_over_time(internal_thread_busy_event_creator_fraction{environment=\"$network\", node_id=~\"$NodeID\"}[$__range]))",
     "legendFormat": "Min"
    },
    {
     "expr": "avg(internal_thread_busy_event_creator_fraction{environment=\"$network\", node_id=~\"$NodeID\"})",
     "legendFormat": "Avg"
    },
    {
     "expr": "max(max_over_time(internal_thread_busy_event_creator_fraction{environment=\"$network\", node_id=~\"$NodeID\"}[$__range]))",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "eventCreatorQueue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 77 },
   "targets": [
    {
     "expr": "internal_event_creator_queueMaxSize{environment=\"$network\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  {
   "title": "eventCreatorQueue",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 77 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(min_over_time(internal_event_creator_queueMaxSize{environment=\"$network\", node_id=~\"$NodeID\"}[$__range]))",
     "legendFormat": "Min"
    },
    {
     "expr": "avg(internal_event_creator_queueMaxSize{environment=\"$network\", node_id=~\"$NodeID\"})",
     "legendFormat": "Avg"
    },
    {
     "expr": "max(max_over_time(internal_event_creator_queueMaxSize{environment=\"$network\", node_id=~\"$NodeID\"}[$__range]))",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Event creator: unhandled task count",
   "type": "timeseries",
   "description": "Number of tasks waiting to be handled by the event creation manager",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 85 },
   "targets": [
    {
     "expr": "platform_eventCreationManager_unhandled_task_count{environment=\"$network\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  { "title": "PreConsensus Event Writer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 } },
  {
   "title": "eventWriter Busy Fraction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 94 },
   "targets": [
    {
     "expr": "internal_thread_busy_event_writer_fraction{environment=\"$network\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  {
   "title": "eventWriter Busy Fraction",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 94 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(min_over_time(internal_thread_busy_event_writer_fraction{environment=\"$network\", node_id=~\"$NodeID\"}[$__range]))",
     "legendFormat": "Min"
    },
    {
     "expr": "avg(internal_thread_busy_event_writer_fraction{environment=\"$network\", node_id=~\"$NodeID\"})",
     "legendFormat": "Avg"
    },
    {
     "expr": "max(max_over_time(internal_thread_busy_event_writer_fraction{environment=\"$network\", node_id=~\"$NodeID\"}[$__range]))",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "PCES writer: unhandled task count",
   "type": "timeseries",
   "description": "Number of tasks waiting to be handled by the PCES writer",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 102 },
   "targets": [
    {
     "expr": "platform_pcesWriter_unhandled_task_count{environment=\"$network\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  { "title": "Consensus Handling", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 110 } },
  {
   "title": "consEvents Busy Fraction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 111 },
   "targets": [
    {
     "expr": "internal_thread_busy_thread_cons_fraction{environment=\"$network\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  {
   "title": "consEvents Busy Fraction",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 111 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(min_over_time(internal_thread_busy_thread_cons_fraction{environment=\"$network\", node_id=~\"$NodeID\"}[$__range]))",
     "legendFormat": "Min"
    },
    {
     "expr": "avg(internal_thread_busy_thread_cons_fraction{environment=\"$network\", node_id=~\"$NodeID\"})",
     "legendFormat": "Avg"
    },
    {
     "expr": "max(max_over_time(internal_thread_busy_thread_cons_fraction{environment=\"$network\", node_id=~\"$NodeID\"}[$__range]))",
     "legendFormat": "Max"
    }
   ]
  },
  { "gridPos": { "h": 8, "w": 16, "x": 0, "y": 119 } },
  {
   "title": "consEvents",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 119 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(min_over_time(internal_consEventsMAX{environment=\"$network\", node_id=~\"$NodeID\"}[$__range]))",
     "legendFormat": "Min"
    },
    {
     "expr": "avg(internal_consEventsMAX{environment=\"$network\", node_id=~\"$NodeID\"})",
     "legendFormat": "Avg"
    },
    {
     "expr": "max(max_over_time(internal_consEventsMAX{environment=\"$network\", node_id=~\"$NodeID\"}[$__range]))",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "handleThread - total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 127 },
   "targets": [
    {
     "expr": "internal_consRound_total{environment=\"$network\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  {
   "title": "handleThread - dataPropagation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 135 },
   "targets": [
    {
     "expr": "internal_consRound_dataPropMillis_per_round{environment=\"$network\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  {
   "title": "handleThread - keystoneFlush",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 143 },
   "targets": [
    {
     "expr": "internal_consRound_keystoneFlushMillis_per_round{environment=\"$network\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  {
   "title": "handleThread - runningHash",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 151 },
   "targets": [
    {
     "expr": "internal_consRound_hashMillis_per_round{environment=\"$network\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  {
   "title": "handleThread - handleTransactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 159 },
   "targets": [
    {
     "expr": "internal_consRound_handleMillis_per_round{environment=\"$network\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  {
   "title": "handleThread - buildState",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 167 },
   "targets": [
    {
     "expr": "internal_consRound_buildStateMillis{environment=\"$network\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  {
   "title": "handleThread - forSigClean",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 175 },
   "targets": [
    {
     "expr": "internal_consRound_forSigCleanMillis{environment=\"$network\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  { "title": "State Hashing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 183 } },
  {
   "title": "stateHashSign Busy Fraction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 184 },
   "targets": [
    {
     "expr": "internal_thread_busy_state_hash_sign_fraction{environment=\"$network\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  {
   "title": "stateHashSign Busy Fraction",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 184 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(min_over_time(internal_thread_busy_state_hash_sign_fraction{environment=\"$network\", node_id=~\"$NodeID\"}[$__range]))",
     "legendFormat": "Min"
    },
    {
     "expr": "avg(internal_thread_busy_state_hash_sign_fraction{environment=\"$network\", node_id=~\"$NodeID\"})",
     "legendFormat": "Avg"
    },
    {
     "expr": "max(max_over_time(internal_thread_busy_state_hash_sign_fraction{environment=\"$network\", node_id=~\"$NodeID\"}[$__range]))",
     "legendFormat": "Max"
    }
   ]
  },
  { "title": "Platform Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 192 } },
  {
   "title": "statusStateMachine Busy Fraction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 193 },
   "targets": [
    {
     "expr": "internal_thread_busy_status_state_machine_fraction{environment=\"$network\", node_id=~\"$NodeID\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  {
   "title": "statusStateMachine Busy Fraction",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 193 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(min_over_time(internal_thread_busy_status_state_machine_fraction{environment=\"$network\", node_id=~\"$NodeID\"}[$__range]))",
     "legendFormat": "Min"
    },
    {
     "expr": "avg(internal_thread_busy_status_state_machine_fraction{environment=\"$network\", node_id=~\"$NodeID\"})",
     "legendFormat": "Avg"
    },
    {
     "expr": "max(max_over_time(internal_thread_busy_status_state_machine_fraction{environment=\"$network\", node_id=~\"$NodeID\"}[$__range]))",
     "legendFormat": "Max"
    }
   ]
  }
 ]
}