{
 "title": "Block Stream Metrics (CN -> BN)",
 "description": "Collection of metrics related to block streaming from consensus nodes to block nodes.",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "NodeId",
    "label": "NodeId",
    "query": {
     "query": "label_values({environment=\"$environment\"},node)"
    }
   },
   { "name": "environment", "query": { "query": "label_values(environment)" } },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Platform Status",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "platform_PlatformStatus{environment=\"$environment\", node_id=~\"$NodeId\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  {
   "title": "trans/sec",
   "type": "timeseries",
   "description": "The number of app transactions added to the hashgraph per second by each node via deduplicated events.",
   "gridPos": { "h": 7, "w": 13, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "platform_trans_per_sec{environment=\"$environment\", type=\"mean\", node_id=~\"$NodeId\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  {
   "title": "Avg trans/sec",
   "type": "stat",
   "description": "The average number of app transactions added to the hashgraph per second by the network via deduplicated events.",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(platform_trans_per_sec{environment=\"$environment\", type=\"mean\", node_id=~\"$NodeId\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Block Buffer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Saturation Percent",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "max by(node) (blockStream_buffer_saturation{node=~\"$NodeId\", environment=\"$environment\"})",
     "legendFormat": "node {{node}}"
    }
   ]
  },
  {
   "title": "Buffer State",
   "type": "state-timeline",
   "description": "0 = OK, 1 = Action Stage, 2 = Recovering, 3 = Back Pressure Enabled",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "max by(node) (blockStream_buffer_backPressureState{node=~\"$NodeId\", environment=\"$environment\"})",
     "legendFormat": "node {{node}}"
    }
   ]
  },
  {
   "title": "Block Buffer Size (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "blockStream_buffer_totalBytes{node=~\"$NodeId\", environment=\"$environment\"}",
     "legendFormat": "node {{node}}"
    }
   ]
  },
  {
   "title": "Block Buffer Size (Blocks)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "blockStream_buffer_numBlocks{node=~\"$NodeId\", environment=\"$environment\"}",
     "legendFormat": "node {{node}}"
    }
   ]
  },
  {
   "title": "Blocks Pending Acknowledgement",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "blockStream_buffer_numBlocksPendingAck{node=~\"$NodeId\", environment=\"$environment\"}",
     "legendFormat": "node {{node}}"
    }
   ]
  },
  {
   "title": "Latest Block Opened",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "max by(node) (blockStream_buffer_latestBlockOpened{node=~\"$NodeId\", environment=\"$environment\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Latest Block Acked",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 27 },
   "targets": [
    {
     "expr": "max by(node) (blockStream_buffer_latestBlockAcked{node=~\"$NodeId\", environment=\"$environment\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Oldest Buffered Block",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "max by(node) (blockStream_buffer_oldestBlock{node=~\"$NodeId\", environment=\"$environment\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Newest Buffered Block",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 27 },
   "targets": [
    {
     "expr": "max by(node) (blockStream_buffer_newestBlock{node=~\"$NodeId\", environment=\"$environment\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Lastest BlockEnd Sent vs. Latest Block Ack'd",
   "type": "timeseries",
   "description": "Lastest BlocEnd Sent (LBS)\nLatest Block Acknowledged (LBA)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "blockStream_connSend_latestBlockEndOfBlock{environment=\"$environment\", node=~\"$NodeId\"}",
     "legendFormat": "{{node}} LBS"
    },
    {
     "expr": "blockStream_buffer_latestBlockAcked{environment=\"$environment\", node=~\"$NodeId\"}",
     "legendFormat": "{{node}} LBA"
    }
   ]
  },
  {
   "title": "Block Size bytes (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "blockStream_buffer_blockBytes{node=~\"$NodeId\", environment=\"$environment\", type=\"mean\"}",
     "legendFormat": "node {{node}}"
    }
   ]
  },
  {
   "title": "Blocks Opened (1m delta)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "max by(node) (delta(blockStream_buffer_numBlocksOpened_total{node=~\"$NodeId\", environment=\"$environment\"}[1m]))",
     "legendFormat": "node {{node}}"
    }
   ]
  },
  {
   "title": "BlockItems per Block (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "blockStream_buffer_blockItemsPerBlock{node=~\"$NodeId\", environment=\"$environment\", type=\"mean\"}",
     "legendFormat": "node {{node}}"
    }
   ]
  },
  {
   "title": "Blocks Closed (1m delta)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "max by(node) (delta(blockStream_buffer_numBlocksClosed_total{node=~\"$NodeId\", environment=\"$environment\"}[1m]))",
     "legendFormat": "node {{node}}"
    }
   ]
  },
  {
   "title": "BlockItem size (bytes Avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "blockStream_buffer_blockItemBytes{node=~\"$NodeId\", environment=\"$environment\", type=\"mean\"}",
     "legendFormat": "node {{node}}"
    }
   ]
  },
  {
   "title": "Blocks Pruned (1m delta)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "max by(node) (delta(blockStream_buffer_numBlocksPruned_total{node=~\"$NodeId\", environment=\"$environment\"}[1m]))",
     "legendFormat": "node {{node}}"
    }
   ]
  },
  {
   "title": "Blocks Missing (1m delta)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "targets": [
    {
     "expr": "max by(node) (delta(blockStream_buffer_numBlocksMissing_total{node=~\"$NodeId\", environment=\"$environment\"}[1m]))",
     "legendFormat": "node {{node}}"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "BlockHeader Sent <-> BlockEnd Sent (µs)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "blockStream_conn_headerSentToBlockEndSentLatency{node=~\"$NodeId\", environment=\"$environment\", type=\"mean\"}",
     "legendFormat": "node {{node}}"
    }
   ]
  },
  {
   "title": "BlockHeader Produced <-> BlockAcknowledgement (µs)",
   "type": "timeseries",
   "description": "The time in µs from producing the BlockHeader to receiving the BlockAcknowledgement",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "blockStream_conn_headerProducedToAckLatency{node=~\"$NodeId\", environment=\"$environment\", type=\"mean\"}",
     "legendFormat": "node {{node}}"
    }
   ]
  },
  {
   "title": "BlockHeader Sent <-> BlockAcknowledgement (µs)",
   "type": "timeseries",
   "description": "The time in µs from sending the BlockHeader to receiving the BlockAcknowledgement",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "blockStream_conn_headerSentToAckLatency{node=~\"$NodeId\", environment=\"$environment\", type=\"mean\"}",
     "legendFormat": "node {{node}}"
    }
   ]
  },
  {
   "title": "Block Closed <-> BlockAcknowledgement (µs)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "blockStream_conn_blockClosedToAckLatency{node=~\"$NodeId\", environment=\"$environment\", type=\"mean\"}",
     "legendFormat": "node {{node}}"
    }
   ]
  },
  {
   "title": "BlockEnd Sent <-> BlockAcknowledgement (µs)",
   "type": "timeseries",
   "description": "The time in µs from sending the BlockEnd to receiving the BlockAcknowledgement",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "blockStream_conn_blockEndSentToAckLatency{node=~\"$NodeId\", environment=\"$environment\", type=\"mean\"}",
     "legendFormat": "node {{node}}"
    }
   ]
  },
  {
   "title": "PublishStreamRequest Latency Mean (µs) (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avg_over_time(blockStream_connSend_requestSendLatency{node=~\"$NodeId\", environment=\"$environment\", type=\"mean\"}[1m])",
     "legendFormat": "node {{node}}"
    }
   ]
  },
  {
   "title": "High latency events for the current active connection (1m delta)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
   "targets": [
    {
     "expr": "max by(node) (delta(blockStream_conn_highLatencyEvents_total{node=~\"$NodeId\"}[1m]))",
     "legendFormat": "node {{node}}"
    }
   ]
  },
  {
   "title": "Pipeline Operation Timeouts",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 93 },
   "targets": [
    {
     "expr": "max by(node) (blockStream_conn_pipelineOperationTimeout_total{node=~\"$NodeId\", environment=\"$environment\"})",
     "legendFormat": "{{node}}"
    },
    {}
   ]
  },
  { "title": "Connectivity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 } },
  {
   "title": "Block Node Connections (CN -> BN)",
   "type": "state-timeline",
   "description": "Which block node is the active connection for each consensus node",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 102 },
   "targets": [
    {
     "expr": "max by(node) (blockStream_conn_activeConnIp{node=~\"$NodeId\", environment=\"$environment\"})",
     "legendFormat": "node {{node}}"
    }
   ]
  },
  {
   "title": "Connections Opened (1m delta)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 102 },
   "targets": [
    {
     "expr": "max by(node) (delta(blockStream_conn_opened_total{node=~\"$NodeId\", environment=\"$environment\"}[1m]))",
     "legendFormat": "node {{node}}"
    }
   ]
  },
  {
   "title": "Connection Create Errors (1m delta)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 110 },
   "targets": [
    {
     "expr": "max by(node) (delta(blockStream_conn_createFailure_total{node=~\"$NodeId\", environment=\"$environment\"}[1m]))",
     "legendFormat": "node {{node}}"
    }
   ]
  },
  {
   "title": "Connections Closed (1m delta)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 110 },
   "targets": [
    {
     "expr": "max by(node) (delta(blockStream_conn_closed_total{node=~\"$NodeId\", environment=\"$environment\"}[1m]))",
     "legendFormat": "node {{node}}"
    }
   ]
  },
  {
   "title": "Connection OnComplete (1m delta)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 118 },
   "targets": [
    {
     "expr": "max by(node) (delta(blockStream_conn_onComplete_total{node=~\"$NodeId\", environment=\"$environment\"}[1m]))",
     "legendFormat": "node {{node}}"
    }
   ]
  },
  {
   "title": "Connection OnError (1m delta)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 118 },
   "targets": [
    {
     "expr": "max by(node) (delta(blockStream_conn_onError_total{node=~\"$NodeId\", environment=\"$environment\"}[1m]))",
     "legendFormat": "node {{node}}"
    }
   ]
  },
  {
   "title": "Connection EndOfStream Limit Exceeded (1m delta)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 126 },
   "targets": [
    {
     "expr": "max by(node) (delta(blockStream_conn_endOfStreamLimitExceeded_total{node=~\"$NodeId\", environment=\"$environment\"}[1m]))",
     "legendFormat": "node {{node}}"
    }
   ]
  },
  {
   "title": "Connection Close Reason (1m delta)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 126 },
   "targets": [
    {
     "expr": "max by(node) (delta(blockStream_conn_connClose_blockNodeBehind_total{node=~\"$NodeId\", environment=\"$environment\"}[1m]))",
     "legendFormat": "node {{node}} (BlockNodeBehind)"
    },
    {
     "expr": "max by(node) (delta(blockStream_conn_connClose_blockNodeHighLatency_total{node=~\"$NodeId\", environment=\"$environment\"}[1m]))",
     "legendFormat": "node {{node}} (HighLatency)"
    },
    {
     "expr": "max by(node) (delta(blockStream_conn_connClose_bufferSaturation_total{node=~\"$NodeId\", environment=\"$environment\"}[1m]))",
     "legendFormat": "node {{node}} (BufferSaturation)"
    },
    {
     "expr": "max by(node) (delta(blockStream_conn_connClose_configUpdate_total{node=~\"$NodeId\", environment=\"$environment\"}[1m]))",
     "legendFormat": "node {{node}} (ConfigUpdate)"
    },
    {
     "expr": "max by(node) (delta(blockStream_conn_connClose_connectionError_total{node=~\"$NodeId\", environment=\"$environment\"}[1m]))",
     "legendFormat": "node {{node}} (ConnectionError)"
    },
    {
     "expr": "max by(node) (delta(blockStream_conn_connClose_tooManyEndStreamResponses_total{node=~\"$NodeId\", environment=\"$environment\"}[1m]))",
     "legendFormat": "node {{node}} (TooManyEndStreamResponses)"
    },
    {
     "expr": "max by(node) (delta(blockStream_conn_connClose_endStreamReceived_total{node=~\"$NodeId\", environment=\"$environment\"}[1m]))",
     "legendFormat": "node {{node}} (EndStreamReceived)"
    },
    {
     "expr": "max by(node) (delta(blockStream_conn_connClose_transientEndStreamReceived_total{node=~\"$NodeId\", environment=\"$environment\"}[1m]))",
     "legendFormat": "node {{node}} (TransientEndStreamReceived)"
    },
    {
     "expr": "max by(node) (delta(blockStream_conn_connClose_higherPriorityFound_total{node=~\"$NodeId\", environment=\"$environment\"}[1m]))",
     "legendFormat": "node {{node}} (HigherPriorityFound)"
    },
    {
     "expr": "max by(node) (delta(blockStream_conn_connClose_internalError_total{node=~\"$NodeId\", environment=\"$environment\"}[1m]))",
     "legendFormat": "node {{node}} (InternalError)"
    },
    {
     "expr": "max by(node) (delta(blockStream_conn_connClose_periodicReset_total{node=~\"$NodeId\", environment=\"$environment\"}[1m]))",
     "legendFormat": "node {{node}} (PeriodicReset)"
    },
    {
     "expr": "max by(node) (delta(blockStream_conn_connClose_newConnection_total{node=~\"$NodeId\", environment=\"$environment\"}[1m]))",
     "legendFormat": "node {{node}} (NewConnection)"
    },
    {
     "expr": "max by(node) (delta(blockStream_conn_connClose_shutdown_total{node=~\"$NodeId\", environment=\"$environment\"}[1m]))",
     "legendFormat": "node {{node}} (Shutdown)"
    },
    {
     "expr": "max by(node) (delta(blockStream_conn_connClose_unknown_total{node=~\"$NodeId\", environment=\"$environment\"}[1m]))",
     "legendFormat": "node {{node}} (Unknown)"
    },
    {
     "expr": "max by(node) (delta(blockStream_conn_connClose_timeout_total{node=~\"$NodeId\", environment=\"$environment\"}[1m]))",
     "legendFormat": "node {{node}} (Timeout)"
    }
   ]
  },
  { "title": "Responses (From Block Node)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 134 } },
  {
   "title": "Unknown Type Responses Received (1m delta)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 135 },
   "targets": [
    {
     "expr": "max by(node) (delta(blockStream_connRecv_unknown_total{node=~\"$NodeId\", environment=\"$environment\"}[1m]))",
     "legendFormat": "node {{node}}"
    }
   ]
  },
  {
   "title": "Acknowledgement Responses Received (1m delta)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 135 },
   "targets": [
    {
     "expr": "max by(node) (delta(blockStream_connRecv_acknowledgement_total{node=~\"$NodeId\", environment=\"$environment\"}[1m]))",
     "legendFormat": "node {{node}}"
    }
   ]
  },
  {
   "title": "SkipBlock Responses Received (1m delta)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 143 },
   "targets": [
    {
     "expr": "max by(node) (delta(blockStream_connRecv_skipBlock_total{node=~\"$NodeId\", environment=\"$environment\"}[1m]))",
     "legendFormat": "node {{node}}"
    }
   ]
  },
  {
   "title": "ResendBlock Responses Received (1m delta)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 143 },
   "targets": [
    {
     "expr": "max by(node) (delta(blockStream_connRecv_resendBlock_total{node=~\"$NodeId\", environment=\"$environment\"}[1m]))",
     "legendFormat": "node {{node}}"
    }
   ]
  },
  {
   "title": "EndStream:Success Responses Received (1m delta)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 151 },
   "targets": [
    {
     "expr": "max by(node) (delta(blockStream_connRecv_endStream_success_total{node_id=~\"$NodeId\", environment=\"$environment\"}[1m]))",
     "legendFormat": "node {{node}}"
    }
   ]
  },
  {
   "title": "EndStream:InvalidRequest Responses Received (1m delta)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 151 },
   "targets": [
    {
     "expr": "max by(node) (delta(blockStream_connRecv_endStream_invalidRequest_total{node=~\"$NodeId\", environment=\"$environment\"}[1m]))",
     "legendFormat": "node {{node}}"
    }
   ]
  },
  {
   "title": "EndStream:Error Responses Received (1m delta)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 159 },
   "targets": [
    {
     "expr": "max by(node) (delta(blockStream_connRecv_endStream_error_total{node=~\"$NodeId\", environment=\"$environment\"}[1m]))",
     "legendFormat": "node {{node}}"
    }
   ]
  },
  {
   "title": "EndStream:Timeout Responses Received (1m delta)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 159 },
   "targets": [
    {
     "expr": "max by(node) (delta(blockStream_connRecv_endStream_timeout_total{node=~\"$NodeId\", environment=\"$environment\"}[1m]))",
     "legendFormat": "node {{node}}"
    }
   ]
  },
  {
   "title": "EndStream:Timeout Responses Received (1m delta)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 167 },
   "targets": [
    {
     "expr": "max by(node) (delta(blockStream_connRecv_endStream_timeout_total{node=~\"$NodeId\", environment=\"$environment\"}[1m]))",
     "legendFormat": "node {{node}}"
    }
   ]
  },
  {
   "title": "EndStream:DuplicateBlock Responses Received (1m delta)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 167 },
   "targets": [
    {
     "expr": "max by(node) (delta(blockStream_connRecv_endStream_duplicateBlock_total{node=~\"$NodeId\", environment=\"$environment\"}[1m]))",
     "legendFormat": "node {{node}}"
    }
   ]
  },
  {
   "title": "EndStream:BadBlockProof Responses Received (1m delta)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 175 },
   "targets": [
    {
     "expr": "max by(node) (delta(blockStream_connRecv_endStream_badBlockProof_total{node=~\"$NodeId\", environment=\"$environment\"}[1m]))",
     "legendFormat": "node {{node}}"
    }
   ]
  },
  {
   "title": "Latest Block received in ResendBlock",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 175 },
   "targets": [
    {
     "expr": "max by(node) (blockStream_connRecv_latestBlockResendBlock{node=~\"$NodeId\", environment=\"$environment\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Latest Block received in SkipBlock",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 175 },
   "targets": [
    {
     "expr": "max by(node) (blockStream_connRecv_latestBlockSkipBlock{node=~\"$NodeId\", environment=\"$environment\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "EndStream:PersistenceFailed Responses Received (1m delta)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 183 },
   "targets": [
    {
     "expr": "max by(node) (delta(blockStream_connRecv_endStream_persistenceFailed_total{node=~\"$NodeId\", environment=\"$environment\"}[1m]))",
     "legendFormat": "node {{node}}"
    }
   ]
  },
  {
   "title": "Latest Block received in NodeBehindPublisher",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 183 },
   "targets": [
    {
     "expr": "max by(node) (blockStream_connRecv_latestBlockBehindPublisher{node=~\"$NodeId\", environment=\"$environment\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Latest Block received in EndOfStream",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 183 },
   "targets": [
    {
     "expr": "max by(node) (blockStream_connRecv_latestBlockEndOfStream{node=~\"$NodeId\", environment=\"$environment\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  { "title": "Requests (To Block Node)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 191 } },
  {
   "title": "Block Items Sent (1m delta)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 192 },
   "targets": [
    {
     "expr": "max by(node) (delta(blockStream_connSend_blockItemCount_total{node=~\"$NodeId\", environment=\"$environment\"}[1m]))",
     "legendFormat": "node {{node}}"
    }
   ]
  },
  {
   "title": "PublishStreamRequest size (byte Avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 192 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "blockStream_connSend_requestBytes{node=~\"$NodeId\", environment=\"$environment\", type=\"mean\"}",
     "legendFormat": "node {{node}}"
    }
   ]
  },
  {
   "title": "Request Send Failures (1m delta)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 200 },
   "targets": [
    {
     "expr": "max by(node) (delta(blockStream_connSend_failure_total{node=~\"$NodeId\", environment=\"$environment\"}[1m]))",
     "legendFormat": "node {{node}}"
    }
   ]
  },
  {
   "title": "PublishStreamRequest BlockItems Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 200 },
   "targets": [
    {
     "expr": "blockStream_connSend_requestBlockItemCount{node=~\"$NodeId\", environment=\"$environment\", type=\"mean\"}",
     "legendFormat": "node {{node}}"
    }
   ]
  },
  {
   "title": "BlockItem Requests Sent (1m delta)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 208 },
   "targets": [
    {
     "expr": "max by(node) (delta(blockStream_connSend_blockItems_total{node=~\"$NodeId\", environment=\"$environment\"}[1m]))",
     "legendFormat": "node {{node}}"
    }
   ]
  },
  {
   "title": "EndStream:Error Requests Sent (1m delta)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 208 },
   "targets": [
    {
     "expr": "max by(node) (delta(blockStream_connSend_endStream_error_total{node=~\"$NodeId\", environment=\"$environment\"}[1m]))",
     "legendFormat": "node {{node}}"
    }
   ]
  },
  {
   "title": "EndStream:Reset Requests Sent (1m delta)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 216 },
   "targets": [
    {
     "expr": "max by(node) (delta(blockStream_connSend_endStream_reset_total{node=~\"$NodeId\", environment=\"$environment\"}[1m]))",
     "legendFormat": "node {{node}}"
    }
   ]
  },
  {
   "title": "EndStream:Timeout Requests Sent (1m delta)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 216 },
   "targets": [
    {
     "expr": "max by(node) (delta(blockStream_connSend_endStream_timeout_total{node=~\"$NodeId\", environment=\"$environment\"}[1m]))",
     "legendFormat": "node {{node}}"
    }
   ]
  },
  {
   "title": "EndStream:TooFarBehind Requests Sent (1m delta)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 224 },
   "targets": [
    {
     "expr": "max by(node) (delta(blockStream_connSend_endStream_tooFarBehind_total{node=~\"$NodeId\", environment=\"$environment\"}[1m]))",
     "legendFormat": "node {{node}}"
    }
   ]
  },
  {
   "title": "Streaming Block Number",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 224 },
   "targets": [
    {
     "expr": "max by(node) (blockStream_connSend_streamingBlockNumber{node=~\"$NodeId\", environment=\"$environment\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  { "title": "Wrapped Record File Hashes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 232 } },
  {
   "title": "Lowest/Highest Block Number Wrapped Hashes",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 233 },
   "targets": [
    {
     "expr": "blockStream_recordHashes_lowestBlock{node=~\"$NodeId\", environment=\"$environment\"}",
     "legendFormat": "{{node}}"
    },
    {
     "expr": "blockStream_recordHashes_highestBlock{node=~\"$NodeId\", environment=\"$environment\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Wrapped Record File Block Hashes Gap Detection",
   "type": "state-timeline",
   "description": "0 = No gaps\n1= Gap exists in wrapped block hashes, refer to hgcaa log for more information",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 233 },
   "targets": [
    {
     "expr": "max by(node) (blockStream_buffer_backPressureState{node=~\"$NodeId\", environment=\"$environment\"})",
     "legendFormat": "node {{node}}"
    }
   ]
  }
 ]
}