{
 "title": "Throttle Utilization",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "Network", "query": { "query": "label_values(environment)" } }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "##### All visualizations on this dashboard show the average utilization over the time period selected."
   }
  },
  {
   "title": "Overview",
   "type": "bargauge",
   "description": "These statistics show the average usage of the time period selected.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "avg(app_consThroughputLimitsPercentUsed{environment=\"$Network\"})",
     "legendFormat": "app_consThroughputLimitsPercentUsed"
    },
    {
     "expr": "avg(app_hapiThroughputLimitsPercentUsed{environment=\"$Network\"})",
     "legendFormat": "app_hapiThroughputLimitsPercentUsed"
    },
    {
     "expr": "avg(app_hapiCreationLimitsPercentUsed{environment=\"$Network\"})",
     "legendFormat": "app_hapiCreationLimitsPercentUsed"
    },
    {
     "expr": "avg(app_hapiFreeQueryLimitsPercentUsed{environment=\"$Network\"})",
     "legendFormat": "app_hapiFreeQueryLimitsPercentUsed"
    },
    {
     "expr": "avg(app_hapiOffHeapQueryLimitsPercentUsed{environment=\"$Network\"})",
     "legendFormat": "app_hapiOffHeapQueryLimitsPercentUsed"
    }
   ]
  },
  {
   "title": "app_consThroughputLimitsPercentUsed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(app_consThroughputLimitsPercentUsed{environment=\"$Network\"})",
     "legendFormat": "app_consThroughputLimitsPercentUsed"
    }
   ]
  },
  {
   "title": "app_consThroughputLimitsPercentUsed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "avg(app_consThroughputLimitsPercentUsed{environment=\"$Network\"})",
     "legendFormat": "app_consThroughputLimitsPercentUsed"
    }
   ]
  },
  {
   "title": "app_hapiThroughputLimitsPercentUsed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(app_hapiThroughputLimitsPercentUsed{environment=\"$Network\"})",
     "legendFormat": "app_hapiThroughputLimitsPercentUsed"
    }
   ]
  },
  {
   "title": "app_hapiThroughputLimitsPercentUsed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "avg(app_hapiThroughputLimitsPercentUsed{environment=\"$Network\"})"
    }
   ]
  },
  {
   "title": "app_hapiCreationLimitsPercentUsed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(app_hapiCreationLimitsPercentUsed{environment=\"$Network\"})",
     "legendFormat": "app_hapiCreationLimitsPercentUsed"
    }
   ]
  },
  {
   "title": "app_hapiCreationLimitsPercentUsed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "avg(app_hapiCreationLimitsPercentUsed{environment=\"$Network\"})",
     "legendFormat": "app_hapiCreationLimitsPercentUsed"
    }
   ]
  },
  {
   "title": "app_hapiFreeQueryLimitsPercentUsed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": " avg(app_hapiFreeQueryLimitsPercentUsed{environment=\"$Network\"})",
     "legendFormat": "app_hapiFreeQueryLimitsPercentUsed"
    }
   ]
  },
  {
   "title": "app_hapiFreeQueryLimitsPercentUsed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "avg(app_hapiFreeQueryLimitsPercentUsed{environment=\"$Network\"})"
    }
   ]
  },
  {
   "title": "app_hapiOffHeapQueryLimitsPercentUsed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(app_hapiOffHeapQueryLimitsPercentUsed{environment=\"$Network\"})",
     "legendFormat": "app_hapiOffHeapQueryLimitsPercentUsed"
    }
   ]
  },
  {
   "title": "app_hapiOffHeapQueryLimitsPercentUsed",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "avg(app_hapiOffHeapQueryLimitsPercentUsed{environment=\"$Network\"})",
     "legendFormat": "app_hapiOffHeapQueryLimitsPercentUsed"
    }
   ]
  }
 ]
}