// SPDX-License-Identifier: Apache-2.0
package org.hiero.consensus.hashgraph.impl.consensus.calculations;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.net.URISyntaxException;
import java.net.URL;
import java.nio.file.FileSystemNotFoundException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.CodeSource;
import java.time.Instant;
import java.time.ZoneOffset;
import java.util.*;

import org.hiero.consensus.hashgraph.impl.consensus.calculations.HashgraphInfo.EventInfo;
import org.hiero.consensus.hashgraph.impl.consensus.calculations.HashgraphInfo.EventInfo.UpdateResults;
import org.hiero.consensus.hashgraph.impl.consensus.calculations.HashgraphInfo.RoundInfo;
import org.hiero.consensus.hashgraph.impl.consensus.calculations.HashgraphInfo.RoundInfoPrev;

/** Class to output and check a log file for checking the consensus calculations in {@link HashgraphInfo HashgraphInfo}.
 * Set the filenames to read and write (or "" to disable the read or write) with INPUT_FILENAME and OUTPUT_FILENAME.
 * The CSV log file is in the same directory as this source file (if this file is at path DESCENT).
 * <p>
 * The output CSV file is in the format described by logFormat.md, which is also in this directory.
 */
public class TestHashgraphInfo {
    /** generate the random hashgraph using this PRNG seed, for repeatability */
    private static final long RANDOM_SEED = 1;

    /** the filename to write (or "" if none) including the extension but not the path */
    private static final String OUTPUT_FILENAME = "test.csv";

    /** the filename to read (or "" if none) including the extension but not the path */
    private static final String INPUT_FILENAME = "test.csv";

    /** the version of this file (increment when the file format changes, or possibly for big algorithm changes) */
    private static final long SOFTWARE_VERSION = 1;

    /** how many events to write to the log file */
    private static final int NUM_EVENTS_TO_WRITE = 100;

    /** the ancestor directory to search upward for */
    private static final String REPOSITORY_DIRECTORY_NAME = "hiero-consensus-node";

    /** the directories to descend through, starting at {@link #REPOSITORY_DIRECTORY_NAME} */
    private static final List<String> DESCENT = List.of(
            "platform-sdk",
            "consensus-hashgraph-impl",
            "src",
            "main",
            "java",
            "org",
            "hiero",
            "consensus",
            "hashgraph",
            "impl",
            "consensus",
            "calculations");



    /** NewHashgraphRow is a CSV row starting with this number */
    private static final int NEW_HASHGRAPH_ROW_TYPE = 0;

    /** RoundInfoPrev is a CSV row starting with this number */
    private static final int ROUND_INFO_PREV_TYPE = 1;

    /** RoundInfo is a CSV row starting with this number */
    private static final int ROUND_INFO_TYPE = 2;

    /** EventInfo is a CSV row starting with this number */
    private static final int EVENT_SIGNED_TYPE = 3;

    /** EventInfo is a CSV row starting with this number */
    private static final int EVENT_INFO_TYPE = 4;

    /** UpdateResults is a CSV row starting with this number */
    private static final int UPDATE_RESULTS_TYPE = 5;

    /**
     * Create random hashgraphs, and update the events repeatedly to reach consensus. Write all the results to
     * the CSV (Comma Separated Values) file. Then read it back in and check it. The main use case is to create
     * it here and then check it by OCaml code that was automatically generated by Rocq from the formalized
     * proof that the Hashgraph consensus algorithm is ABFT.
     *
     */
     static void main() throws IOException {
        if (!OUTPUT_FILENAME.isEmpty()) {
            createLogFile(OUTPUT_FILENAME);
        }
        if (!INPUT_FILENAME.isEmpty()) {
            checkLogFile(INPUT_FILENAME);
        }
    }

    /**
     * Find the Path of the test log file. This is found by starting where the
     * compiled class is located and then searching upward until the REPOSITORY_DIRECTORY_NAME directory is found,
     * then searching back downward through the directories in DESCENT.
     *
     * @param outputFilename the filename (with extension but without a path) of the test CSV log file
     * @return the Path, or null if anything went wrong, in which case an error has already been printed
     */
    private static Path getFilePath(String outputFilename) {
        // Find the directory holding the compiled class, which is where the upward search starts.
        // This is independent of the working directory the JVM happens to be launched from.
        final CodeSource codeSource =
                TestHashgraphInfo.class.getProtectionDomain().getCodeSource();
        final URL location = codeSource == null ? null : codeSource.getLocation();
        if (location == null) {
            System.out.println("ERROR: the location of the compiled class is unavailable - no file was written");
            return null;
        }

        final Path path;
        try {
            path = Path.of(location.toURI());
        } catch (final URISyntaxException | IllegalArgumentException | FileSystemNotFoundException e) {
            System.out.println(
                    "ERROR: the compiled class is not at a local file path: " + location + " - no file was written");
            return null;
        }

        // the location is a directory of class files, or a jar, in which case start at its parent
        final Path start = Files.isDirectory(path) ? path : path.getParent();
        if (start == null) {
            return null;
        }

        // walk up to the repository directory
        Path directory = start;
        while (directory != null && !REPOSITORY_DIRECTORY_NAME.equals(String.valueOf(directory.getFileName()))) {
            directory = directory.getParent();
        }
        if (directory == null) {
            System.out.println("ERROR: no ancestor directory named \"" + REPOSITORY_DIRECTORY_NAME
                    + "\" was found above " + start + " - no file was written");
            return null;
        }

        // walk back down, checking each directory exists
        for (final String name : DESCENT) {
            directory = directory.resolve(name);
            if (!Files.isDirectory(directory)) {
                System.out.println("ERROR: directory does not exist: " + directory + " - no file was written");
                return null;
            }
        }

        // if no errors so far, then create the file here.
        return directory.resolve(outputFilename);
    }

    /**
     * Data for a row of the CSV file that is written each time a new hashgraph is created.
     *
     * @param softwareVersion the version of TestHashgraphInfo used to create the CSV log file
     * @param randomSeed the random number generator seed used to generate all the data in the CSV log file
     * @param time the time when the CSV log file was created
     */
    private record NewHashgraphRow(long softwareVersion, long randomSeed, Instant time) {}

    /** return the eventID of an event, or -1 if null */
    private static long eventID(EventInfo event) {
        return event == null ? -1 : event.getEventID();
    }

    /** append to the CSV line an array of events (length then each eventID) with comma before but not after */
    private static void appendEvents(StringBuilder line, EventInfo[] events) {
        line.append(",").append(events.length);
        for (EventInfo event : events) {
            line.append(",").append(eventID(event));
        }
    }

    /** append to the CSV line an array of longs (length then each long) with comma before but not after */
    private static void appendLongs(StringBuilder line, long[] longs) {
        line.append(",").append(longs.length);
        for (Long n : longs) {
            line.append(",").append(n);
        }
    }

    /**
     * Append to the CSV line the first len elements of an array of booleans (length then each as 0=false 1=true)
     * with a comma before but not after.
     */
    private static void appendBooleans(StringBuilder line, boolean[] booleans, int len) {
        line.append(",").append(len);
        for (int i = 0; i < len; i++) {
            line.append(",").append(booleans[i] ? 1 : 0);
        }
    }

    /** write one line of the CSV file describing the RoundInfoPrev fields */
    private static void writeNewHashgraphRow(PrintWriter out, NewHashgraphRow newHashgraphRow) {
        StringBuilder line = new StringBuilder();
        line.append(NEW_HASHGRAPH_ROW_TYPE);
        line.append(",").append(newHashgraphRow.softwareVersion());
        line.append(",").append(newHashgraphRow.randomSeed());
        line.append(",").append(newHashgraphRow.time().atZone(ZoneOffset.UTC).getYear());
        line.append(",").append(newHashgraphRow.time().atZone(ZoneOffset.UTC).getMonth().getValue());
        line.append(",").append(newHashgraphRow.time().atZone(ZoneOffset.UTC).getDayOfMonth());
        line.append(",").append(newHashgraphRow.time().atZone(ZoneOffset.UTC).getHour());
        line.append(",").append(newHashgraphRow.time().atZone(ZoneOffset.UTC).getMinute());
        line.append(",").append(newHashgraphRow.time().atZone(ZoneOffset.UTC).getSecond());
        line.append(",").append(newHashgraphRow.time().getNano());
        out.println(line);
    }

        /** write one line of the CSV file describing the RoundInfoPrev fields */
    private static void writeRoundInfoPrev(PrintWriter out, RoundInfoPrev roundInfoPrev) {
        StringBuilder line = new StringBuilder();
        line.append(ROUND_INFO_PREV_TYPE);
        line.append(",").append(roundInfoPrev.pendingRound());
        line.append(",").append(roundInfoPrev.prevJudgeCon1() ? 1 : 0);
        appendEvents(line, roundInfoPrev.prevJudges());
        line.append(",").append(roundInfoPrev.prevJudgesCopied() ? 1 : 0);
        line.append(",").append(roundInfoPrev.prevMinNonAncientRound());
        line.append(",").append(roundInfoPrev.prevNumCons());
        line.append(",").append(roundInfoPrev.prevMinJudgeBirthRound());
        out.println(line);
    }

    /** write one line of the CSV file describing the RoundInfo fields */
    private static void writeRoundInfo(PrintWriter out, RoundInfo roundInfo) {
        StringBuilder line = new StringBuilder();
        line.append(ROUND_INFO_TYPE);
        line.append(",").append(roundInfo.pendingRound());
        appendLongs(line, roundInfo.nodes());
        appendLongs(line, roundInfo.stake());
        line.append(",").append(roundInfo.seeNum());
        line.append(",").append(roundInfo.seeDen());
        line.append(",").append(roundInfo.judgeCon1() ? 1 : 0);
        line.append(",").append(roundInfo.coinInterval());
        line.append(",").append(roundInfo.targetNumRoundsNonAncient());
        line.append(",").append(roundInfo.numRoundsAddressBook());
        out.println(line);
    }

    /** return one line of the CSV file describing the EventInfo fields in the signed events, before updating */
    private static void writeEventSigned(PrintWriter out, EventInfo eventInfo) {
        StringBuilder line = new StringBuilder();
        line.append(EVENT_SIGNED_TYPE);
        line.append(",").append(eventID(eventInfo));
        // payload skipped because it doesn't affect consensus and has no simple way to put in a CSV
        line.append(",").append(eventInfo.getTimeCreated().getEpochSecond());
        line.append(",").append(eventInfo.getTimeCreated().getNano());
        line.append(",").append(eventInfo.getCreatorNodeID());
        line.append(",").append(eventInfo.getBirthRound());
        line.append(",").append(eventInfo.getCoin());
        appendEvents(line, eventInfo.getParentsSigned());
        // parentBirthRounds, parentCreators, signature skipped because they don't affect consensus
        out.println(line);
    }

    /**
     * Return one line of the CSV file describing the given EventInfo with calculated memoized fields.
     * This must be called immediately after eventInfo.update(...) because some fields are read from the hashgraph.
     */
    private static void writeEventInfo(PrintWriter out, EventInfo eventInfo, RoundInfoPrev roundInfoPrev) {
        StringBuilder line = new StringBuilder();
        HashgraphInfo h = eventInfo.getHashgraph();
        line.append(EVENT_INFO_TYPE);
        line.append(",").append(eventID(eventInfo));
        line.append(",").append(eventInfo.getCreatorIndex());
        line.append(",").append(eventID(eventInfo.getSelfParent()));
        line.append(",").append(eventInfo.getMaxJudgeRound());
        appendEvents(line, h.getParents().toArray(EventInfo[]::new));
        line.append(",").append(h.getTotalStake());
        line.append(",").append(h.getMinNonAncientRound());
        line.append(",").append(h.getVoteD());
        appendBooleans(line, eventInfo.getAncestorJudge(), roundInfoPrev.prevJudges().length);
        line.append(",").append(eventInfo.getGen());
        appendEvents(line, eventInfo.getLastSee());
        appendEvents(line, eventInfo.getStronglySeeP());
        line.append(",").append(eventInfo.getVotingRound());
        line.append(",").append(eventID(eventInfo.getFirstSelfWitnessS()));
        line.append(",").append(eventID(eventInfo.getFirstWitnessS()));
        appendEvents(line, eventInfo.getStronglySeeS1());
        appendEvents(line, eventInfo.getVoteE());
        appendBooleans(line, eventInfo.getVoteB(), eventInfo.getVoteB().length);
        line.append(",").append(eventInfo.isConsensus() ? 1 : 0);
        line.append(",").append(eventInfo.getConsensusOrder());
        Instant t = eventInfo.getConsensusTimestamp();
        line.append(",").append(t == null ? -1 : t.getEpochSecond());
        line.append(",").append(t == null ? -1 : t.getNano());
        out.println(line);
    }

    /** return one line of the CSV file describing the given EventInfo with calculated memoized fields */
    private static void writeUpdateResults(PrintWriter out, UpdateResults updateResults) {
        StringBuilder line = new StringBuilder();
        line.append(UPDATE_RESULTS_TYPE);
        appendEvents(line, updateResults.consensusEvents());
        line.append(",").append(updateResults.roundTimestamp().getEpochSecond());
        line.append(",").append(updateResults.roundTimestamp().getNano());
        line.append(",").append(updateResults.voteD());
        line.append(",").append(updateResults.usedCoin() ? 1 : 0);
        // skip roundInfoPrev because it is a line of its own
        out.println(line);
    }

    /**
     * Check that the log file correctly matches the calculations done by HashgraphInfo. This can be used to
     * check for regressions after code changes.
     */
    static void checkLogFile(String inputFilename) {
        Path inputFile = getFilePath(inputFilename);
        if (inputFile == null) {
            return;
        }
        try (final BufferedReader in = Files.newBufferedReader(inputFile)) {
            String line;
            while ((line = in.readLine()) != null) {
                for (final String field : line.split(",")) {
                    final long number = Long.parseLong(field.trim());
                    System.out.print(number + " ");
                }
                System.out.println();
            }
        } catch (Exception e) {
            System.out.println("ERROR: while reading " + inputFile + " - " + e);
            for (StackTraceElement stackLine : e.getStackTrace()) {
                System.out.println(stackLine.toString());
            }
            return;
        }

        System.out.println("read " + inputFile);
    }

    /**
     * Create random hashgraphs, and update the events repeatedly to reach consensus. Write all the results to
     * the CSV (Comma Separated Values) file.
     * <p>
     * This finds that directory by starting where this compiled class is, then doing "cd .." repeatedly until it finds
     * the directory hiero-consensus-node, then going down into the directory
     * hiero-consensus-node/platform-sdk/consensus-hashgraph-impl/src/main/java/
     * org/hiero/consensus/hashgraph/impl/consensus/calculations/log and creates the file there.
     */
    static void createLogFile(String outputFilename) throws IOException {
        final int MAX_NODE_ID = 999;
        final int NUM_NODES = 4;
        final int MAX_OTHER_PARENTS = 2;
        final Path outputFile = getFilePath(outputFilename);
        if (outputFile == null) {
            return;
        }
        try (final PrintWriter out = new PrintWriter(Files.newBufferedWriter(outputFile))) {
            final Random random = new Random(RANDOM_SEED);
            final EventInfo[] lastEvent = new EventInfo[NUM_NODES]; // the most recent event created by each node
            HashgraphInfo hashgraphInfo = new HashgraphInfo();
            List<EventInfo> recentEvents = new LinkedList<>();
            HashMap<Long, EventInfo> mapIdToEventInfo = new HashMap<Long, EventInfo>();
            HashMap<Long, HashMap<Long, Integer>> mapRoundNodeIdToNodeIndex = new HashMap<Long, HashMap<Long, Integer>>();
            HashMap<Long, HashMap<Integer, Long>> mapRoundNodeIndexToNodeId = new HashMap<Long, HashMap<Integer, Long>>();
            HashMap<Long, Integer> mapCurrNodeIdToNodeIndex; // = new HashMap<Long, Integer>();
            HashMap<Integer, Long> mapCurrNodeIndexToNodeId; // = new HashMap<Integer, Long>();
            UpdateResults updateResults;
            long nextEventID  = 1;
            long eventsWritten = 0; //number of times an EventInfo row has been written so far
            boolean newHashgraph = true;
            boolean newRound = true;
            RoundInfo roundInfo = null;

            //fields for the next roundInfo
            long[] roundInfoNodes = new long[] {100, 200, 300, 400};
            long[] roundInfoStake = new long[] {101, 102, 103, 104};
            int roundInfoCoinInterval = 10;
            int roundInfoSeeNum = 3;
            int roundInfoSeeDen = 3;
            boolean roundInfoJudgeCon1 = false;
            int roundInfoTargetNumRoundsNonAncient = 5;
            int roundInfoNumRoundsAddressBook = 2;

            RoundInfoPrev roundInfoPrev = HashgraphInfo.FIRST_ROUND_INFO_PREV;

            while (eventsWritten < NUM_EVENTS_TO_WRITE) {
                if (newHashgraph) {
                    writeNewHashgraphRow(out, new NewHashgraphRow(SOFTWARE_VERSION, RANDOM_SEED, Instant.now()));
                    newHashgraph = false;
                }
                if (newRound) {
//                    for (int i=roundInfoNodes.length-1; i>0; i--) { // randomly shuffle the order of nodes and stake
//                        int p = random.nextInt(i+1);
//                        long t1 = roundInfoNodes[i];
//                        long t2 = roundInfoStake[i];
//                        roundInfoNodes[i] = roundInfoNodes[p];
//                        roundInfoStake[i] = roundInfoStake[p];
//                        roundInfoNodes[p] = t1;
//                        roundInfoStake[p] = t2;
//                    }
                    roundInfo = new RoundInfo(roundInfoPrev.pendingRound(),
                            roundInfoNodes, roundInfoStake, roundInfoCoinInterval, roundInfoSeeNum,
                            roundInfoSeeDen, roundInfoJudgeCon1, roundInfoTargetNumRoundsNonAncient,
                            roundInfoNumRoundsAddressBook);
                    writeRoundInfoPrev(out, roundInfoPrev);
                    writeRoundInfo(out, roundInfo);
                    newRound = false;
                }
                int creatorIndex = random.nextInt(roundInfo.nodes().length);
                ArrayList<EventInfo> possibleOtherParents = new ArrayList<>();
                ArrayList<EventInfo> parents = new ArrayList<EventInfo>();
                if (lastEvent[creatorIndex] != null) {
                    parents.add(lastEvent[creatorIndex]);
                }
                for (int i=0; i<lastEvent.length; i++) {
                    if (lastEvent[i] != null && i != creatorIndex) {
                        possibleOtherParents.add(lastEvent[i]);
                    }
                }
                Collections.shuffle(possibleOtherParents, random);
                parents.addAll(possibleOtherParents.subList(0, Math.min(possibleOtherParents.size(), MAX_OTHER_PARENTS)));

                EventInfo eventInfo = new EventInfo(
                        hashgraphInfo, // HashgraphInfo hashgraphInfo
                        nextEventID++, // long eventID
                        roundInfoNodes[creatorIndex], // int creatorNodeID
                        Instant.now(), // Instant timeCreated
                        roundInfo.pendingRound(), // long birthRound
                        random.nextInt(), // int coin
                        parents.toArray(new EventInfo[0]), // EventInfo[] parents
                        null); // Object payload
                //lastEvent[(int)roundInfo.nodes()[eventInfo.getCreatorIndex()]] = eventInfo;
                mapIdToEventInfo.put(eventInfo.getEventID(), eventInfo);
                recentEvents.add(eventInfo);
                writeEventSigned(out, eventInfo);
                lastEvent[creatorIndex] = eventInfo;

                updateResults = eventInfo.update(roundInfo, roundInfoPrev);
                writeEventInfo(out, eventInfo, roundInfoPrev);
                eventsWritten++;
                if (updateResults != null) {
                    writeUpdateResults(out, updateResults);
                    roundInfoPrev = updateResults.nextRoundInfoPrev();
                    newRound = true;
                    for (EventInfo event : updateResults.consensusEvents()) {
                        writeEventInfo(out, event, roundInfoPrev);
                        eventsWritten++;
                    }
                    writeRoundInfoPrev(out, roundInfoPrev);
                }
            }
        }
        System.out.println("wrote " + outputFile);
    }
}
