{
 "title": "Block Stream Metrics (CN -> BN)",
 "description": "Collections of metrics related to block streaming from consensus nodes to block nodes.",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "NodeId", "label": "NodeId", "query": { "query": "label_values(node)" } }
  ]
 },
 "panels": [
  { "title": "Block Buffer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Saturation Percent",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max by(node) (blockStream_buffer_saturation{node=~\"$NodeId\"})",
     "legendFormat": "node {{node}}"
    }
   ]
  },
  {
   "title": "Buffer State",
   "type": "state-timeline",
   "description": "0 = OK, 1 = Action Stage, 2 = Recovering, 3 = Back Pressure Enabled",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "max by(node) (blockStream_buffer_backPressureState{node=~\"$NodeId\"})",
     "legendFormat": "node {{node}}"
    }
   ]
  },
  {
   "title": "Latest Block Opened",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "max by(node) (blockStream_buffer_latestBlockOpened{node=~\"$NodeId\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Latest Block Acked",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 10 },
   "targets": [
    {
     "expr": "max by(node) (blockStream_buffer_latestBlockAcked{node=~\"$NodeId\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Oldest Buffered Block",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "max by(node) (blockStream_buffer_oldestBlock{node=~\"$NodeId\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Newest Buffered Block",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 10 },
   "targets": [
    {
     "expr": "max by(node) (blockStream_buffer_newestBlock{node=~\"$NodeId\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Blocks Opened (1m delta)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "max by(node) (delta(blockStream_buffer_numBlocksOpened_total{node=~\"$NodeId\"}[1m]))",
     "legendFormat": "node {{node}}"
    }
   ]
  },
  {
   "title": "Blocks Closed (1m delta)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "max by(node) (delta(blockStream_buffer_numBlocksClosed_total{node=~\"$NodeId\"}[1m]))",
     "legendFormat": "node {{node}}"
    }
   ]
  },
  {
   "title": "Blocks Pruned (1m delta)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "max by(node) (delta(blockStream_buffer_numBlocksPruned_total{node=~\"$NodeId\"}[1m]))",
     "legendFormat": "node {{node}}"
    }
   ]
  },
  {
   "title": "Blocks Missing (1m delta)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "max by(node) (delta(blockStream_buffer_numBlocksMissing_total{node=~\"$NodeId\"}[1m]))",
     "legendFormat": "node {{node}}"
    }
   ]
  },
  {
   "title": "BlockAcknowledgement Latency (ms)",
   "type": "timeseries",
   "description": "The time in ms from sending the BlockProof to receiving the BlockAcknowledgement",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "max by(node) (blockStream_conn_acknowledgementLatency{node=~\"$NodeId\"})",
     "legendFormat": "node {{node}}"
    }
   ]
  },
  { "title": "Connectivity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Block Node Connections (CN -> BN)",
   "type": "state-timeline",
   "description": "Which block node is the active connection for each consensus node",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "max by(node) (blockStream_conn_activeConnIp{node=~\"$NodeId\"})",
     "legendFormat": "node {{node}}"
    }
   ]
  },
  {
   "title": "Connections Opened (1m delta)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "expr": "max by(node) (delta(blockStream_conn_opened_total{node=~\"$NodeId\"}[1m]))",
     "legendFormat": "node {{node}}"
    }
   ]
  },
  {
   "title": "Missing Active Connections (1m delta)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "max by(node) (delta(blockStream_conn_noActive_total{node=~\"$NodeId\"}[1m]))",
     "legendFormat": "node {{node}}"
    }
   ]
  },
  {
   "title": "Connections Closed (1m delta)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "expr": "max by(node) (delta(blockStream_conn_closed_total{node=~\"$NodeId\"}[1m]))",
     "legendFormat": "node {{node}}"
    }
   ]
  },
  {
   "title": "Connection Create Errors (1m delta)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "max by(node) (delta(blockStream_conn_createFailure_total{node=~\"$NodeId\"}[1m]))",
     "legendFormat": "node {{node}}"
    }
   ]
  },
  {
   "title": "Connection OnError (1m delta)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "targets": [
    {
     "expr": "max by(node) (delta(blockStream_conn_onError_total{node=~\"$NodeId\"}[1m]))",
     "legendFormat": "node {{node}}"
    }
   ]
  },
  {
   "title": "Connection OnComplete (1m delta)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "max by(node) (delta(blockStream_conn_onComplete_total{node=~\"$NodeId\"}[1m]))",
     "legendFormat": "node {{node}}"
    }
   ]
  },
  {
   "title": "Connection EndOfStream Limit Exceeded (1m delta)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "targets": [
    {
     "expr": "max by(node) (delta(blockStream_conn_endOfStreamLimitExceeded_total{node=~\"$NodeId\"}[1m]))",
     "legendFormat": "node {{node}}"
    }
   ]
  },
  {
   "title": "High latency events for the current active connection (1m delta)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "targets": [
    {
     "expr": "max by(node) (delta(blockStream_conn_highLatencyEvents_total{node=~\"$NodeId\"}[1m]))",
     "legendFormat": "node {{node}}"
    }
   ]
  },
  { "title": "Responses (From Block Node)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 } },
  {
   "title": "Unknown Type Responses Received (1m delta)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
   "targets": [
    {
     "expr": "max by(node) (delta(blockStream_connRecv_unknown_total{node=~\"$NodeId\"}[1m]))",
     "legendFormat": "node {{node}}"
    }
   ]
  },
  {
   "title": "Acknowledgement Responses Received (1m delta)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
   "targets": [
    {
     "expr": "max by(node) (delta(blockStream_connRecv_acknowledgement_total{node=~\"$NodeId\"}[1m]))",
     "legendFormat": "node {{node}}"
    }
   ]
  },
  {
   "title": "SkipBlock Responses Received (1m delta)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
   "targets": [
    {
     "expr": "max by(node) (delta(blockStream_connRecv_skipBlock_total{node=~\"$NodeId\"}[1m]))",
     "legendFormat": "node {{node}}"
    }
   ]
  },
  {
   "title": "ResendBlock Responses Received (1m delta)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 93 },
   "targets": [
    {
     "expr": "max by(node) (delta(blockStream_connRecv_resendBlock_total{node=~\"$NodeId\"}[1m]))",
     "legendFormat": "node {{node}}"
    }
   ]
  },
  {
   "title": "EndStream:Success Responses Received (1m delta)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
   "targets": [
    {
     "expr": "max by(node) (delta(blockStream_connRecv_endStream_success_total{node=~\"$NodeId\"}[1m]))",
     "legendFormat": "node {{node}}"
    }
   ]
  },
  {
   "title": "EndStream:InvalidRequest Responses Received (1m delta)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 101 },
   "targets": [
    {
     "expr": "max by(node) (delta(blockStream_connRecv_endStream_invalidRequest_total{node=~\"$NodeId\"}[1m]))",
     "legendFormat": "node {{node}}"
    }
   ]
  },
  {
   "title": "EndStream:Error Responses Received (1m delta)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 109 },
   "targets": [
    {
     "expr": "max by(node) (delta(blockStream_connRecv_endStream_error_total{node=~\"$NodeId\"}[1m]))",
     "legendFormat": "node {{node}}"
    }
   ]
  },
  {
   "title": "EndStream:Timeout Responses Received (1m delta)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 109 },
   "targets": [
    {
     "expr": "max by(node) (delta(blockStream_connRecv_endStream_timeout_total{node=~\"$NodeId\"}[1m]))",
     "legendFormat": "node {{node}}"
    }
   ]
  },
  {
   "title": "EndStream:Timeout Responses Received (1m delta)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 117 },
   "targets": [
    {
     "expr": "max by(node) (delta(blockStream_connRecv_endStream_timeout_total{node=~\"$NodeId\"}[1m]))",
     "legendFormat": "node {{node}}"
    }
   ]
  },
  {
   "title": "EndStream:DuplicateBlock Responses Received (1m delta)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 117 },
   "targets": [
    {
     "expr": "max by(node) (delta(blockStream_connRecv_endStream_duplicateBlock_total{node=~\"$NodeId\"}[1m]))",
     "legendFormat": "node {{node}}"
    }
   ]
  },
  {
   "title": "EndStream:BadBlockProof Responses Received (1m delta)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 125 },
   "targets": [
    {
     "expr": "max by(node) (delta(blockStream_connRecv_endStream_badBlockProof_total{node=~\"$NodeId\"}[1m]))",
     "legendFormat": "node {{node}}"
    }
   ]
  },
  {
   "title": "EndStream:Behind Responses Received (1m delta)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 125 },
   "targets": [
    {
     "expr": "max by(node) (delta(blockStream_connRecv_endStream_behind_total{node=~\"$NodeId\"}[1m]))",
     "legendFormat": "node {{node}}"
    }
   ]
  },
  {
   "title": "EndStream:PersistenceFailed Responses Received (1m delta)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 133 },
   "targets": [
    {
     "expr": "max by(node) (delta(blockStream_connRecv_endStream_persistenceFailed_total{node=~\"$NodeId\"}[1m]))",
     "legendFormat": "node {{node}}"
    }
   ]
  },
  { "title": "Requests (To Block Node)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 141 } },
  {
   "title": "Block Items Sent (1m delta)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 142 },
   "targets": [
    {
     "expr": "max by(node) (delta(blockStream_connSend_blockItemCount_total{node=~\"$NodeId\"}[1m]))",
     "legendFormat": "node {{node}}"
    }
   ]
  },
  {
   "title": "PublishStreamRequest Latency Mean (ms) (1m)",
   "type": "timeseries",
   "description": "The running average of PublishStreamRequest latency in ms as measured from submission to PBJ Pipeline.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 142 },
   "targets": [
    {
     "expr": "avg_over_time(blockStream_connSend_publishStreamRequestLatency{type=\"mean\"}[1m])",
     "legendFormat": "node {{node}}"
    }
   ]
  },
  {
   "title": "Request Send Failures (1m delta)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 150 },
   "targets": [
    {
     "expr": "max by(node) (delta(blockStream_connSend_failure_total{node=~\"$NodeId\"}[1m]))",
     "legendFormat": "node {{node}}"
    }
   ]
  },
  {
   "title": "EndStream:Error Requests Sent (1m delta)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 150 },
   "targets": [
    {
     "expr": "max by(node) (delta(blockStream_connSend_endStream_error_total{node=~\"$NodeId\"}[1m]))",
     "legendFormat": "node {{node}}"
    }
   ]
  },
  {
   "title": "BlockItem Requests Sent (1m delta)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 158 },
   "targets": [
    {
     "expr": "max by(node) (delta(blockStream_connSend_blockItems_total{node=~\"$NodeId\"}[1m]))",
     "legendFormat": "node {{node}}"
    }
   ]
  },
  {
   "title": "EndStream:Timeout Requests Sent (1m delta)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 158 },
   "targets": [
    {
     "expr": "max by(node) (delta(blockStream_connSend_endStream_timeout_total{node=~\"$NodeId\"}[1m]))",
     "legendFormat": "node {{node}}"
    }
   ]
  },
  {
   "title": "EndStream:Reset Requests Sent (1m delta)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 166 },
   "targets": [
    {
     "expr": "max by(node) (delta(blockStream_connSend_endStream_reset_total{node=~\"$NodeId\"}[1m]))",
     "legendFormat": "node {{node}}"
    }
   ]
  },
  {
   "title": "EndStream:TooFarBehind Requests Sent (1m delta)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 174 },
   "targets": [
    {
     "expr": "max by(node) (delta(blockStream_connSend_endStream_tooFarBehind_total{node=~\"$NodeId\"}[1m]))",
     "legendFormat": "node {{node}}"
    }
   ]
  }
 ]
}