FROM eclipse-temurin:25-jre

RUN apt-get update && \
    apt-get install -y --no-install-recommends libsodium23 && \
    rm -rf /var/lib/apt/lists/*

ENV MALLOC_ARENA_MAX=2

WORKDIR /opt/hedera/services

COPY . .

RUN chmod +x start-small-memory.sh && \
    mkdir -p output

EXPOSE 50211 50212

CMD ["./start-small-memory.sh"]
