apiVersion: 1

datasources:
  - name: benchmark-metrics
    uid: PF31BFB237EDD2252
    type: marcusolsson-csv-datasource
    access: proxy
    url: /benchmark-data/BenchmarkMetrics.csv
    jsonData:
      storage: local
