// SPDX-License-Identifier: Apache-2.0
package com.hedera.node.app.service.contract.impl.test;

import java.util.concurrent.ThreadLocalRandom;
import org.apache.tuweni.bytes.Bytes32;

public final class TestByteUtils {

    private TestByteUtils() {}

    private static final ThreadLocalRandom RANDOM = ThreadLocalRandom.current();

    /**
     * Generate random byte array for the tests
     *
     * @param length of the generated byte array
     * @return random byte array
     */
    public static byte[] randomBytes(final int length) {
        final byte[] bytes = new byte[length];
        RANDOM.nextBytes(bytes);
        return bytes;
    }

    /**
     * Generate random EVM address for the tests
     *
     * @return random EVM address
     */
    public static byte[] randomAddressBytes() {
        return randomBytes(20);
    }

    /**
     * Generate random EVM storage key for the tests
     *
     * @return random EVM storage key
     */
    public static Bytes32 randomKeyBytes32() {
        return Bytes32.wrap(randomBytes(32));
    }
}
