stream_over_http_enabled: true
server:
  http_listen_port: 3200
  log_level: info

query_frontend:
  search:
    # The number of concurrent jobs to execute when searching the backend.
    # (default: 1000)
    concurrent_jobs: 4

    # query_backend_after and query_ingesters_until together control where the query-frontend searches for traces.
    # Time ranges before query_ingesters_until will be searched in the ingesters only.
    # Time ranges after query_backend_after will be searched in the backend/object storage only.
    # Time ranges from query_backend_after through query_ingesters_until will be queried from both locations.
    # query_backend_after must be less than or equal to query_ingesters_until.
    # (default: 15m)
    query_backend_after: 0m     # Search backend storage immediately
    # (default: 30m)
    query_ingesters_until: 24h  # Keep searching ingesters for data up to 24h old

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: "tempo:4317"

ingester:
  # amount of time a trace must be idle before flushing it to the wal.
  # (default: 10s)
  trace_idle_period: 3s
  # how often to sweep all tenants and move traces from live -> wal -> completed blocks.
  # (default: 10s)
  flush_check_period: 3s
  # maximum length of time before cutting a block
  # (default: 30m)
  max_block_duration: 5m
  # duration to keep blocks in the ingester after they have been flushed
  # (default: 15m)
  complete_block_timeout: 30s # Closes blocks after 15s of inactivity

compactor:
  compaction:
    block_retention: 24h # overall Tempo trace retention. set for demo purposes

metrics_generator:
  registry:
    external_labels:
      source: tempo
      cluster: docker-compose
  storage:
    path: /var/tempo/generator/wal
    remote_write:
      - url: http://prometheus:9090/api/v1/write
        send_exemplars: true
  traces_storage:
    path: /var/tempo/generator/traces

storage:
  trace:
    backend: local # backend configuration to use
    wal:
      path: /var/tempo/wal # where to store the wal locally
    local:
      path: /var/tempo/blocks

overrides:
  defaults:
    metrics_generator:
      # service-graphs: Creates metrics representing relationships between services
      # span-metrics: Generates metrics from span data
      # local-blocks: Processes locally stored trace blocks
      processors: [service-graphs, span-metrics, local-blocks] # enables metrics generator
      generate_native_histograms: both