{
 "title": "Event creation",
 "time": { "from": "now-1d", "to": "now" },
 "panels": [
  { "title": "Event creation metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total events/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "events_per_sec", "legendFormat": "{{node}}" }
   ]
  },
  {
   "title": "Per node events/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    { "expr": "cEvents_per_sec", "legendFormat": "{{node}}" }
   ]
  },
  {
   "title": "Event Creation Status",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(eventCreation_fraction_ATTEMPTING_CREATION)",
     "legendFormat": "Attempting creation"
    },
    {
     "expr": "avg(eventCreation_fraction_IDLE)",
     "legendFormat": "Idle"
    },
    {
     "expr": "avg(eventCreation_fraction_NO_ELIGIBLE_PARENTS)",
     "legendFormat": "No eligible parents"
    },
    {
     "expr": "avg(eventCreation_fraction_RATE_LIMITED)",
     "legendFormat": "Rate limited"
    },
    {
     "expr": "avg(eventCreation_fraction_PIPELINE_INSERTION)",
     "legendFormat": "Pipeline insertion"
    },
    {
     "expr": "avg(eventCreation_fraction_PLATFORM_STATUS)",
     "legendFormat": "Platform status"
    },
    {
     "expr": "avg(eventCreation_fraction_QUIESCENCE)",
     "legendFormat": "Quiescence"
    },
    {
     "expr": "avg(eventCreation_fraction_OVERLOADED)",
     "legendFormat": "Overloaded"
    },
    {
     "expr": "avg(eventCreation_fraction_ROUND_LAG)",
     "legendFormat": "Round lag"
    }
   ]
  }
 ]
}