{
 "title": "MerkeleDb Compaction",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Hashes Compaction Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "merkle_db:compactions:hashesTime_ms",
     "legendFormat": "level{{level}}"
    }
   ]
  },
  {
   "title": "Hashes Files",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "merkle_db:compactions:hashesFileSize_byte",
     "legendFormat": "level{{level}}"
    }
   ]
  },
  {
   "title": "Leaf Keys Compaction Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "merkle_db:compactions:leafKeysTime_ms",
     "legendFormat": "level{{level}}"
    }
   ]
  },
  {
   "title": "Leaf Keys Files",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "merkle_db:compactions:leafKeysFileSize_byte",
     "legendFormat": "level{{level}}"
    }
   ]
  },
  {
   "title": "Leaves Compaction Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "merkle_db:compactions:leavesTime_ms",
     "legendFormat": "level{{level}}"
    }
   ]
  },
  {
   "title": "Leaves Files",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "merkle_db:compactions:leavesFileSize_byte",
     "legendFormat": "level{{level}}"
    }
   ]
  }
 ]
}