{
 "title": "MerkleDb2",
 "tags": [
  "Platform",
  "PlatformData"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "network", "label": "Network", "query": { "query": "label_values(environment)" } },
   {
    "name": "NodeID",
    "label": "Node ID",
    "query": {
     "query": "label_values({environment=\"$network\"}, node_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "MerkleDb reads / s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(merkle_db:reads:hashes_total{environment=\"$network\", node_id=\"$NodeID\"}[10m])",
     "legendFormat": "hashes"
    },
    {
     "expr": "rate(merkle_db:reads:leafKeys_total{environment=\"$network\", node_id=\"$NodeID\"}[10m])",
     "legendFormat": "leaf keys"
    },
    {
     "expr": "rate(merkle_db:reads:leaves_total{environment=\"$network\", node_id=\"$NodeID\"}[10m])",
     "legendFormat": "leaves"
    }
   ]
  },
  {
   "title": "MerkleDb writes / s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(merkle_db:flushes:hashesWritten_total{environment=\"$network\", node_id=\"$NodeID\"}[10m])",
     "legendFormat": "hashes written"
    },
    {
     "expr": "rate(merkle_db:flushes:leafKeysWritten_total{environment=\"$network\", node_id=\"$NodeID\"}[10m])",
     "legendFormat": "leaf keys written"
    },
    {
     "expr": "rate(merkle_db_2:ds_flushes_leavesDeleted_total{environment=\"$network\", node_id=\"$NodeID\"}[10m])",
     "legendFormat": "leaves deleted"
    },
    {
     "expr": "rate(merkle_db:flushes:leavesWritten_total{environment=\"$network\", node_id=\"$NodeID\"}[10m])",
     "legendFormat": "leaves written"
    }
   ]
  },
  {
   "title": "MerkleDb file size, Mb",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "merkle_db:files:hashesStoreFileSize_byte{environment=\"$network\", node_id=\"$NodeID\"}",
     "legendFormat": "hashes"
    },
    {
     "expr": "merkle_db:files:leafKeysStoreFileSize_byte{environment=\"$network\", node_id=\"$NodeID\"}",
     "legendFormat": "leaf keys"
    },
    {
     "expr": "merkle_db:files:leavesStoreFileSize_byte{environment=\"$network\", node_id=\"$NodeID\"}",
     "legendFormat": "leaves"
    }
   ]
  },
  {
   "title": "MerkleDb file count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "merkle_db:files:hashesStoreFileCount{environment=\"$network\", node_id=\"$NodeID\"}",
     "legendFormat": "hashes"
    },
    {
     "expr": "merkle_db:files:leafKeysStoreFileCount{environment=\"$network\", node_id=\"$NodeID\"}",
     "legendFormat": "leafKeys"
    },
    {
     "expr": "merkle_db:files:leavesStoreFileCount{environment=\"$network\", node_id=\"$NodeID\"}",
     "legendFormat": "leaves"
    }
   ]
  },
  {
   "title": "Offheap usage, Mb",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "merkle_db:offheap:hashesIndexSize_byte{environment=\"$network\", node_id=\"$NodeID\"}",
     "legendFormat": "hash store index"
    },
    {
     "expr": "merkle_db:offheap:hashesListSize_byte{environment=\"$network\", node_id=\"$NodeID\"}",
     "legendFormat": "hashes list"
    },
    {
     "expr": "merkle_db:offheap:leavesIndexSize_byte{environment=\"$network\", node_id=\"$NodeID\"}",
     "legendFormat": "leaves store index"
    },
    {
     "expr": "merkle_db:offheap:objectKeyBucketsIndexSize_byte{environment=\"$network\", node_id=\"$NodeID\"}",
     "legendFormat": "generic key buckets index"
    }
   ]
  }
 ]
}