{
 "title": "MerkleDb",
 "tags": [
  "Platform",
  "PlatformData"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "network", "label": "Network", "query": { "query": "label_values(environment)" } },
   {
    "name": "NodeID",
    "label": "Node ID",
    "query": {
     "query": "label_values({environment=\"$network\"}, node_id)"
    }
   },
   {
    "name": "Store",
    "label": "Virtual Map",
    "query": {
     "query": "metrics(virtual_map_vmap_size_.*)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "MerkleDb reads / s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(merkle_db_ds_reads_hashes_$Store{environment=\"$network\", node_id=\"$NodeID\"}[10m])",
     "legendFormat": "hashes"
    },
    {
     "expr": "rate(merkle_db_ds_reads_leafKeys_$Store{environment=\"$network\", node_id=\"$NodeID\"}[10m])",
     "legendFormat": "leaf keys"
    },
    {
     "expr": "rate(merkle_db_ds_reads_leaves_$Store{environment=\"$network\", node_id=\"$NodeID\"}[10m])",
     "legendFormat": "leaves"
    }
   ]
  },
  {
   "title": "MerkleDb writes / s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(merkle_db_ds_flushes_hashesWritten_$Store{environment=\"$network\", node_id=\"$NodeID\"}[10m])",
     "legendFormat": "hashes written"
    },
    {
     "expr": "rate(merkle_db_ds_flushes_leafKeysWritten_$Store{environment=\"$network\", node_id=\"$NodeID\"}[10m])",
     "legendFormat": "leaf keys written"
    },
    {
     "expr": "rate(merkle_db_ds_flushes_leavesDeleted_$Store{environment=\"$network\", node_id=\"$NodeID\"}[10m])",
     "legendFormat": "leaves deleted"
    },
    {
     "expr": "rate(merkle_db_ds_flushes_leavesWritten_$Store{environment=\"$network\", node_id=\"$NodeID\"}[10m])",
     "legendFormat": "leaves written"
    }
   ]
  },
  {
   "title": "MerkleDb file size, Mb",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "merkle_db_ds_files_hashesStoreFileSizeMb_$Store{environment=\"$network\", node_id=\"$NodeID\"}",
     "legendFormat": "hashes"
    },
    {
     "expr": "merkle_db_ds_files_leafKeysStoreFileSizeMb_$Store{environment=\"$network\", node_id=\"$NodeID\"}",
     "legendFormat": "leaf keys"
    },
    {
     "expr": "merkle_db_ds_files_leavesStoreFileSizeMb_$Store{environment=\"$network\", node_id=\"$NodeID\"}",
     "legendFormat": "leaves"
    }
   ]
  },
  {
   "title": "MerkleDb file count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "merkle_db_ds_files_hashesStoreFileCount_$Store{environment=\"$network\", node_id=\"$NodeID\"}",
     "legendFormat": "hashes"
    },
    {
     "expr": "merkle_db_ds_files_leafKeysStoreFileCount_$Store{environment=\"$network\", node_id=\"$NodeID\"}",
     "legendFormat": "leafKeys"
    },
    {
     "expr": "merkle_db_ds_files_leavesStoreFileCount_$Store{environment=\"$network\", node_id=\"$NodeID\"}",
     "legendFormat": "leaves"
    }
   ]
  },
  {
   "title": "Offheap usage, Mb",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "merkle_db_ds_offheap_hashesIndexMb_$Store{environment=\"$network\", node_id=\"$NodeID\"}",
     "legendFormat": "hash store index"
    },
    {
     "expr": "merkle_db_ds_offheap_hashesListMb_$Store{environment=\"$network\", node_id=\"$NodeID\"}",
     "legendFormat": "hashes list"
    },
    {
     "expr": "merkle_db_ds_offheap_leavesIndexMb_$Store{environment=\"$network\", node_id=\"$NodeID\"}",
     "legendFormat": "leaves store index"
    },
    {
     "expr": "merkle_db_ds_offheap_longKeysIndexMb_$Store{environment=\"$network\", node_id=\"$NodeID\"}",
     "legendFormat": "long keys index"
    },
    {
     "expr": "merkle_db_ds_offheap_objectKeyBucketsIndexMb_$Store{environment=\"$network\", node_id=\"$NodeID\"}",
     "legendFormat": "generic key buckets index"
    }
   ]
  },
  {
   "title": "Offheap usage total, Mb",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "merkle_db_ds_offheap_dataSourceMb_accountStore{environment=\"$network\", node_id=\"$NodeID\"} + merkle_db_ds_offheap_dataSourceMb_fileStore{environment=\"$network\", node_id=\"$NodeID\"} + merkle_db_ds_offheap_dataSourceMb_tokenRelStore{environment=\"$network\", node_id=\"$NodeID\"} + merkle_db_ds_offheap_dataSourceMb_smartContractIterableKvStore{environment=\"$network\", node_id=\"$NodeID\"}",
     "legendFormat": "Total"
    }
   ]
  }
 ]
}