{
 "title": "Store Files Stats",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Store", "label": "StoreName", "query": { "query": "label_values(store_name)" } }
  ]
 },
 "panels": [
  {
   "title": "Files Count",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "merkle_db_files_count{store_name=\"$Store\"}",
     "legendFormat": "level_{{compaction_level}}"
    }
   ]
  },
  {
   "title": "Files Size",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "merkle_db_files_size_byte{store_name=\"$Store\"}",
     "legendFormat": "level_{{compaction_level}}"
    }
   ]
  },
  {
   "title": "Garbage Ratio",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "merkle_db_files_garbage_ratio{store_name=\"$Store\"}",
     "legendFormat": "level_{{compaction_level}}"
    }
   ]
  }
 ]
}