{
 "title": "Store File Stats Comparison By Level",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Store",
    "label": "Store",
    "query": {
     "query": "label_values(merkle_db_files_count,store_name)"
    }
   },
   {
    "name": "CompactionLevel",
    "label": "Compaction Level",
    "query": {
     "query": "label_values(merkle_db_files_count{store_name=\"$Store\"},compaction_level)"
    }
   },
   {
    "name": "NextCompactionLevel",
    "label": "Next Compaction Level",
    "query": {
     "query": "query_result($CompactionLevel + 1)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Files Count",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "merkle_db_files_count{store_name=\"$Store\", compaction_level=\"$CompactionLevel\"}",
     "legendFormat": "level_{{compaction_level}}"
    },
    {
     "expr": "merkle_db_files_count{store_name=\"$Store\", compaction_level=\"$NextCompactionLevel\"}",
     "legendFormat": "level_{{compaction_level}}"
    }
   ]
  },
  {
   "title": "Files Size",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "merkle_db_files_size_byte{store_name=\"$Store\", compaction_level=\"$CompactionLevel\"}",
     "legendFormat": "level_{{compaction_level}}"
    },
    {
     "expr": "merkle_db_files_size_byte{store_name=\"$Store\", compaction_level=\"$NextCompactionLevel\"}",
     "legendFormat": "level_{{compaction_level}}"
    }
   ]
  },
  {
   "title": "Garbage Ratio",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "merkle_db_files_garbage_ratio{store_name=\"$Store\", compaction_level=\"$CompactionLevel\"}",
     "legendFormat": "level_{{compaction_level}}"
    },
    {
     "expr": "merkle_db_files_garbage_ratio{store_name=\"$Store\", compaction_level=\"$NextCompactionLevel\"}",
     "legendFormat": "level_{{compaction_level}}"
    }
   ]
  }
 ]
}