{
 "title": "VirtualMap",
 "tags": [
  "Platform",
  "PlatformData"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "network", "label": "Network", "query": { "query": "label_values(environment)" } },
   {
    "name": "Store",
    "label": "Virtual Map",
    "query": {
     "query": "metrics(virtual_map_vmap_size.*)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Size (entities count)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "virtual_map_vmap_size_$Store{environment=\"$network\", node_id=\"0\"}",
     "legendFormat": "$Store"
    }
   ]
  },
  {
   "title": "Size total (entities count)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "virtual_map_vmap_size_accountStore{environment=\"$network\", node_id=\"0\"}",
     "legendFormat": "accountStore"
    },
    {
     "expr": "virtual_map_vmap_size_fileStore{environment=\"$network\", node_id=\"0\"}",
     "legendFormat": "fileStore"
    },
    {
     "expr": "virtual_map_vmap_size_smartContractIterableKvStore{environment=\"$network\", node_id=\"0\"}",
     "legendFormat": "smartContractIterableKvStore"
    },
    {
     "expr": "virtual_map_vmap_size_tokenRelStore{environment=\"$network\", node_id=\"0\"}",
     "legendFormat": "tokenRelStore"
    },
    {
     "expr": "virtual_map_vmap_size_uniqueTokenStore{environment=\"$network\", node_id=\"0\"}",
     "legendFormat": "uniqueTokenStore"
    }
   ]
  },
  { "title": "Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Reads / s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(virtual_map_vmap_queries_readEntities_$Store{environment=\"$network\"}[10m])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Updates / s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "rate(virtual_map_vmap_queries_addedEntities_$Store{environment=\"$network\"}[10m]) + rate(virtual_map_vmap_queries_updatedEntities_$Store{environment=\"$network\"}[10m]) +\nrate(virtual_map_vmap_queries_removedEntities_$Store{environment=\"$network\"}[10m])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Node cache size, bytes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "virtual_map_vmap_lifecycle_nodeCacheSizeB_$Store{environment=\"$network\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "MerkleDb total file size, Mb",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "merkle_db_ds_files_totalSizeMb_$Store{environment=\"$network\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Copy hash time, ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "virtual_map_vmap_lifecycle_hashDurationMs_$Store{environment=\"$network\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Copy flush time, ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "virtual_map_vmap_lifecycle_flushDurationMs_$Store{environment=\"$network\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Flush backlog backpressure, ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "virtual_map_vmap_lifecycle_flushBackpressureMs_$Store{environment=\"$network\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Family size backpressure, ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "virtual_map_vmap_lifecycle_familySizeBackpressureMs_$Store{environment=\"$network\"}",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}