services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123"   # HTTP
      - "9000:9000"   # Native
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ./clickhouse/data:/var/lib/clickhouse
      - ./clickhouse/logs:/var/log/clickhouse-server
      - ./clickhouse/config.d:/etc/clickhouse-server/config.d
      - ./clickhouse/users.d:/etc/clickhouse-server/users.d
    environment:
      - CLICKHOUSE_DB=telemetry
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - clickhouse
    environment:
      # Installs the ClickHouse datasource plugin at startup
      - GF_INSTALL_PLUGINS=grafana-clickhouse-datasource
      # Optional: default admin creds
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana:/var/lib/grafana
      - ./provisioning:/etc/grafana/provisioning
