



MINIO_CONSOLE_IP=`cat get_svc.txt | grep 'minio-console' | awk '{print $3}'`
MINIO_IP=`cat get_svc.txt | grep -E '^minio[ \t]' | awk '{print $3}'`


cat << EOF | awk '{print "export "$0}' > block_node.env
MINIO_CONSOLE_PORT_9090_TCP_ADDR=$MINIO_CONSOLE_IP
MINIO_CONSOLE_PORT_9090_TCP_PORT=9090
MINIO_SERVICE_PORT=80
MINIO_PORT=tcp://$MINIO_IP:80
MINIO_CONSOLE_PORT_9090_TCP_PROTO=tcp
MINIO_CONSOLE_PORT=tcp://$MINIO_CONSOLE_IP:9090
MINIO_CONSOLE_SERVICE_PORT=9090
MINIO_PORT_80_TCP_ADDR=$MINIO_IP
MINIO_PORT_80_TCP_PORT=80
MINIO_CONSOLE_PORT_9090_TCP=tcp://$MINIO_CONSOLE_IP:9090
MINIO_PORT_80_TCP_PROTO=tcp
MINIO_PORT_80_TCP=tcp://$MINIO_IP:80
MINIO_CONSOLE_SERVICE_PORT_HTTP_CONSOLE=9090
MINIO_SERVICE_PORT_HTTP_MINIO=80
MINIO_SERVICE_HOST=$MINIO_IP
MINIO_CONSOLE_SERVICE_HOST=$MINIO_CONSOLE_IP
PROMETHEUS_ENDPOINT_ENABLED=false
PROMETHEUS_ENDPOINT_PORT_NUMBER=16007
SERVER_PORT=40840
BN_WORKDIR=/opt/hiero/block-node
JAVA_TOOL_OPTIONS=-Djava.util.logging.config.file=/opt/hiero/block-node/logs/config/logging.properties
KUBERNETES_PORT_443_TCP_PORT=443
KUBERNETES_PORT_443_TCP_PROTO=tcp
KUBERNETES_SERVICE_PORT_HTTPS=443
KUBERNETES_SERVICE_PORT=443
LANG=C.UTF-8
LC_ALL=C.UTF-8
MESSAGING_BLOCK_NOTIFICATION_QUEUE_SIZE=16
EOF

for i in $(seq 1 1 7)
do

  haproxy_node_svc=`cat get_svc.txt | grep -E "haproxy-node${i}-svc" | awk '{print $3}'`
  network_node_svc=`cat get_svc.txt | grep -E "network-node${i}-svc" | awk '{print $3}'`
  envoy_proxy_node_svc=`cat get_svc.txt | grep -E "envoy-proxy-node${i}-svc" | awk '{print $3}'`

  cat << EOF | awk '{print "export "$0}' >> block_node.env
NETWORK_NODE${i}_SVC_PORT_50111_TCP=tcp://${network_node_svc}:50111
NETWORK_NODE${i}_SVC_PORT_9090_TCP=tcp://${network_node_svc}:9090
NETWORK_NODE${i}_SVC_PORT_50212_TCP=tcp://${network_node_svc}:50212
NETWORK_NODE${i}_SVC_SERVICE_PORT_GRPC_NON_TLS=50211
ENVOY_PROXY_NODE${i}_SVC_SERVICE_HOST=${envoy_proxy_node_svc}
ENVOY_PROXY_NODE${i}_SVC_PORT_8080_TCP_ADDR=${envoy_proxy_node_svc}
HAPROXY_NODE${i}_SVC_SERVICE_HOST=${haproxy_node_svc}
ENVOY_PROXY_NODE${i}_SVC_PORT_9090_TCP_ADDR=${envoy_proxy_node_svc}
HAPROXY_NODE${i}_SVC_PORT_9090_TCP_ADDR=${haproxy_node_svc}
NETWORK_NODE${i}_SVC_SERVICE_PORT_PROMETHEUS=9090
ENVOY_PROXY_NODE${i}_SVC_PORT_8080_TCP_PORT=8080
HAPROXY_NODE${i}_SVC_PORT_50211_TCP_ADDR=${haproxy_node_svc}
NETWORK_NODE${i}_SVC_SERVICE_PORT_GOSSIP=50111
HAPROXY_NODE${i}_SVC_PORT_50212_TCP_ADDR=${haproxy_node_svc}
ENVOY_PROXY_NODE${i}_SVC_PORT_8080_TCP_PROTO=tcp
HAPROXY_NODE${i}_SVC_SERVICE_PORT_NON_TLS_GRPC_CLIENT_PORT=50211
ENVOY_PROXY_NODE${i}_SVC_PORT_9090_TCP_PORT=9090
ENVOY_PROXY_NODE${i}_SVC_PORT_9090_TCP_PROTO=tcp
HAPROXY_NODE${i}_SVC_PORT_50211_TCP_PORT=50211
HAPROXY_NODE${i}_SVC_PORT_9090_TCP_PORT=9090
HAPROXY_NODE${i}_SVC_PORT_50211_TCP_PROTO=tcp
HAPROXY_NODE${i}_SVC_PORT_50212_TCP_PORT=50212
ENVOY_PROXY_NODE${i}_SVC_SERVICE_PORT=8080
ENVOY_PROXY_NODE${i}_SVC_PORT=tcp://${envoy_proxy_node_svc}:8080
HAPROXY_NODE${i}_SVC_PORT_9090_TCP_PROTO=tcp
HAPROXY_NODE${i}_SVC_SERVICE_PORT=50211
HAPROXY_NODE${i}_SVC_PORT=tcp://${haproxy_node_svc}:50211
HAPROXY_NODE${i}_SVC_PORT_50212_TCP_PROTO=tcp
ENVOY_PROXY_NODE${i}_SVC_PORT_8080_TCP=tcp://${envoy_proxy_node_svc}:8080
ENVOY_PROXY_NODE${i}_SVC_PORT_9090_TCP=tcp://${envoy_proxy_node_svc}:9090
HAPROXY_NODE${i}_SVC_PORT_50211_TCP=tcp://${haproxy_node_svc}:50211
HAPROXY_NODE${i}_SVC_PORT_9090_TCP=tcp://${haproxy_node_svc}:9090
HAPROXY_NODE${i}_SVC_PORT_50212_TCP=tcp://${haproxy_node_svc}:50212
NETWORK_NODE${i}_SVC_SERVICE_PORT_GRPC_TLS=50212
NETWORK_NODE${i}_SVC_SERVICE_HOST=${network_node_svc}
NETWORK_NODE${i}_SVC_PORT_50111_TCP_ADDR=${network_node_svc}
NETWORK_NODE${i}_SVC_PORT_9090_TCP_ADDR=${network_node_svc}
NETWORK_NODE${i}_SVC_PORT_50211_TCP_ADDR=${network_node_svc}
NETWORK_NODE${i}_SVC_PORT_50212_TCP_ADDR=${network_node_svc}
NETWORK_NODE${i}_SVC_PORT_50111_TCP_PORT=50111
NETWORK_NODE${i}_SVC_PORT_50211_TCP_PORT=50211
NETWORK_NODE${i}_SVC_PORT_9090_TCP_PORT=9090
NETWORK_NODE${i}_SVC_PORT_50111_TCP_PROTO=tcp
NETWORK_NODE${i}_SVC_PORT_9090_TCP_PROTO=tcp
NETWORK_NODE${i}_SVC_PORT_50212_TCP_PORT=50212
ENVOY_PROXY_NODE${i}_SVC_SERVICE_PORT_PROMETHEUS=9090
NETWORK_NODE${i}_SVC_PORT_50211_TCP_PROTO=tcp
HAPROXY_NODE${i}_SVC_SERVICE_PORT_PROMETHEUS=9090
NETWORK_NODE${i}_SVC_PORT=tcp://${network_node_svc}:50111
NETWORK_NODE${i}_SVC_PORT_50212_TCP_PROTO=tcp
NETWORK_NODE${i}_SVC_SERVICE_PORT=50111
HAPROXY_NODE${i}_SVC_SERVICE_PORT_TLS_GRPC_CLIENT_PORT=50212
EOF
done

#split prio=1 and prio=2
for i in $(seq 1 1 7)
do

  block_node_ip=`cat get_svc.txt | grep -E "block-node-${i}" | grep -v '\-p2\-' | awk '{print $3}'`

  cat << EOF | awk '{print "export "$0}' >> block_node.env
BLOCK_NODE_${i}_PORT_16007_TCP_ADDR=${block_node_ip}
BLOCK_NODE_${i}_PORT_16007_TCP_PORT=16007
BLOCK_NODE_${i}_PORT_16007_TCP_PROTO=tcp
BLOCK_NODE_${i}_PORT_16007_TCP=tcp://${block_node_ip}:16007
BLOCK_NODE_${i}_PORT_40840_TCP_ADDR=${block_node_ip}
BLOCK_NODE_${i}_PORT_40840_TCP_PORT=40840
BLOCK_NODE_${i}_PORT_40840_TCP_PROTO=tcp
BLOCK_NODE_${i}_PORT_40840_TCP=tcp://${block_node_ip}:40840
BLOCK_NODE_${i}_PORT=tcp://${block_node_ip}:40840
BLOCK_NODE_${i}_SERVICE_HOST=${block_node_ip}
BLOCK_NODE_${i}_SERVICE_PORT_HTTP=40840
BLOCK_NODE_${i}_SERVICE_PORT_METRICS=16007
BLOCK_NODE_${i}_SERVICE_PORT=40840
EOF
done


for i in $(seq 1 1 7)
do

  block_node_ip=`cat get_svc.txt | grep -E "block-node-${i}" | grep '\-p2\-' | awk '{print $3}'`

  j=`expr $i + 7`
  cat << EOF | awk '{print "export "$0}' >> block_node.env
BLOCK_NODE_${j}_PORT_16007_TCP_ADDR=${block_node_ip}
BLOCK_NODE_${j}_PORT_16007_TCP_PORT=16007
BLOCK_NODE_${j}_PORT_16007_TCP_PROTO=tcp
BLOCK_NODE_${j}_PORT_16007_TCP=tcp://${block_node_ip}:16007
BLOCK_NODE_${j}_PORT_40840_TCP_ADDR=${block_node_ip}
BLOCK_NODE_${j}_PORT_40840_TCP_PORT=40840
BLOCK_NODE_${j}_PORT_40840_TCP_PROTO=tcp
BLOCK_NODE_${j}_PORT_40840_TCP=tcp://${block_node_ip}:40840
BLOCK_NODE_${j}_PORT=tcp://${block_node_ip}:40840
BLOCK_NODE_${j}_SERVICE_HOST=${block_node_ip}
BLOCK_NODE_${j}_SERVICE_PORT_HTTP=40840
BLOCK_NODE_${j}_SERVICE_PORT_METRICS=16007
BLOCK_NODE_${j}_SERVICE_PORT=40840
EOF
done