# SPDX-License-Identifier: Apache-2.0
name: "006: [USER] Update GS State Var"
on:
  workflow_dispatch:
    inputs:
      value:
        description: "New value for GS_STATE:"
        required: true

defaults:
  run:
    shell: bash

permissions:
  contents: write

jobs:
  update-gs-state-variable:
    name: Update GS_STATE Variable
    runs-on: hl-cn-default-lin-sm
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: Update GS_STATE to input value
        uses: step-security/set-github-variable@3293f8b09a8468a063a2521be95a09d8c40aa405 # v1.0.2
        with:
          name: "GS_STATE"
          value: ${{ inputs.value }}
          repository: ${{ github.repository }}
          token: ${{ secrets.GH_ACCESS_TOKEN }}
