# SPDX-License-Identifier: Apache-2.0
name: "701: [FLOW] Auto Unapprove PR"
on:
  pull_request:
    types:
      - opened
      - ready_for_review
      - reopened
      - synchronize

defaults:
  run:
    shell: bash

permissions:
  contents: read
  pull-requests: write

jobs:
  auto-unapprove:
    name: Auto Unapprove PR
    runs-on: hl-cn-default-lin-sm
    steps:
      - name: Initialize Job
        uses: pandaswhocode/initialize-github-job@5dbfbc4329ceab48a57d983325dadbd3ec8123e9 # v1.2.2
        with:
          checkout: "true"
          checkout-token: "${{ secrets.GITHUB_TOKEN }}"
          setup-node: "true"
          node-version: "24"

      - name: Dismiss Reviews from Code Owners and Teams
        uses: PandasWhoCode/auto-unapprove-plus@d0cee4be290b1b8b979bfa2447d0633ece8c93f8 # v1.0.0
        with:
          github-token: ${{ secrets.GH_AUTO_UNAPPROVE_TOKEN }}
          team-token: ${{ secrets.TEAM_MEMBERS_TOKEN }}
          pr-number: ${{ github.event.pull_request.number }}
          dry-run: "false"
          code-owners-file: ".codeowners"
          target-branch: ${{ github.event.pull_request.base.ref }}
          # "%" expands to "@<this repository's organization>/", matching the
          # "%<team>" entries in .codeowners.
          team-start-with: "%"
