# SPDX-License-Identifier: Apache-2.0
name: "809: [CALL] Dependency Module Chk"
on:
  workflow_call:
    inputs:
      ref:
        description: "The branch, tag or SHA to checkout."
        required: false
        type: string
      java-distribution:
        description: "Java JDK Distribution:"
        type: string
        required: false
        default: "temurin"
      java-version:
        description: "Java JDK Version:"
        type: string
        required: false
      node-version:
        description: "NodeJS Version:"
        type: string
        required: false
        default: "20"
    secrets:
      access-token:
        description: "The GitHub access token used to checkout the repository, submodules, and make GitHub API calls."
        required: true
      gcp-project-number:
        description: "GCP project for storing Gradle remote cache entries."
        required: true
    outputs:
      failure-mode:
        description: "Failure Mode"
        value: ${{ jobs.dependency-module-check.outputs.failure-mode }}

defaults:
  run:
    shell: bash

permissions:
  id-token: write
  actions: read
  pull-requests: write
  statuses: write
  checks: write
  contents: read

env:
  GCP_PROJECT_NUMBER: ${{ secrets.gcp-project-number }}
  GRADLE_EXEC: ionice -c 2 -n 2 nice -n 19 ./gradlew
  CG_EXEC: ionice -c 2 -n 2 nice -n 19

jobs:
  dependency-module-check:
    name: "Dependency Module Check"
    runs-on: hl-cn-default-lin-md
    outputs:
      failure-mode: ${{ steps.set-failure-mode.outputs.failure-mode }}
    steps:
      - name: Prepare Runner
        id: prepare-runner
        uses: pandaswhocode/initialize-github-job@5dbfbc4329ceab48a57d983325dadbd3ec8123e9 # v1.2.2
        with:
          checkout: "true"
          checkout-ref: "${{ inputs.ref }}"
          checkout-fetch-depth: "1"
          checkout-token: "${{ secrets.access-token }}"
          setup-java: "true"
          java-version: "${{ inputs.java-version }}"
          java-distribution: "${{ inputs.java-distribution }}"
          setup-gradle: "true"
          setup-testlens: "true"
          gradle-cache-read-only: "false"
          setup-node: "true"
          node-version: "${{ inputs.node-version }}"

      - name: Gradle Dependency Scopes Check
        id: check-dependency-scopes
        run: ${GRADLE_EXEC} checkAllModuleInfo checkVersionConsistency validatePomFiles

      - name: Set Failure Mode Output
        id: set-failure-mode
        if: ${{ always() }}
        env:
          INPUT_TEST_OUTCOMES: ${{ steps.check-dependency-scopes.outcome }}
          INPUT_WORKFLOW_OUTCOMES: ${{ steps.prepare-runner.outcome }}
        run: bash .github/workflows/support/scripts/set-failure-mode.sh
