# SPDX-License-Identifier: Apache-2.0
name: "PR Formatting"
on:
  pull_request_target:
    types:
      - assigned
      - unassigned
      - labeled
      - unlabeled
      - opened
      - reopened
      - edited
      - converted_to_draft
      - ready_for_review
      - review_requested
      - review_request_removed
      - locked
      - unlocked
      - synchronize

defaults:
  run:
    shell: bash

permissions:
  statuses: write

jobs:
  title-check:
    name: Title Check
    runs-on: hl-cn-default-lin-sm
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit

      - name: Check PR Title
        uses: step-security/action-semantic-pull-request@75d2dd5deafa3e9fccc1626ecd58d076ed1d2c79 # v6.1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  assignee-check:
    name: Assignee Check
    runs-on: hl-cn-default-lin-sm

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit

      - name: Check Assignee
        if: ${{ github.event.pull_request.assignees == null || github.event.pull_request.assignees[0] == null }}
        run: |
          echo "Assignee is not set. Failing the workflow."
          exit 1

      - name: Get Commit Info
        id: commit-info
        run: |
          COMMIT_SHA=$(git rev-parse HEAD)
          echo "sha=${COMMIT_SHA}" | tee "${GITHUB_OUTPUT}"

      - name: Get Commit Information
        id: fetch-commit-info
        run: |
          COMMIT_SHA="${{ steps.commit-info.sha }}"
          echo "commit-hash=${COMMIT_SHA}" >> "${GITHUB_OUTPUT}"
          echo "commit-author=$(git log -1 --pretty=format:'%an <%ae>' ${COMMIT_SHA})" >> "${GITHUB_OUTPUT}"
          echo "commit-email=$(git log -1 --pretty=format:'%ae' ${COMMIT_SHA})" >> "${GITHUB_OUTPUT}"

      - name: Find Commit Author in Slack
        id: find-commit-author-slack
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_CITR_BOT_TOKEN }}
          EMAIL: ${{ steps.fetch-commit-info.outputs.commit-email }}
        continue-on-error: true
        run: |
          bash "${{ github.workspace }}/.github/workflows/support/scripts/find-commit-author-slack.sh"
          echo "slack-user-id=${SLACK_USER_ID}" >> "${GITHUB_OUTPUT}"
