# SPDX-License-Identifier: Apache-2.0
name: "Node: FSTS Custom Regression"
on:
  workflow_dispatch:
    inputs:
      panel-config:
        description: "JRS Panel Config File (Relative):"
        required: false
        type: string
        default: "configs/services/suites/ci/GCP-Commit-Services-Comp-Basic-4N-1C.json"
      slack-results-channel:
        description: "Slack Test Result Channel:"
        required: false
        type: string
        default: "regression-test"
      slack-summary-channel:
        description: "Slack Summary Channel:"
        required: false
        type: string
        default: "regression-test"
      java-version:
        description: "Java JDK Version:"
        type: string
        required: false
        default: "21.0.6"
      java-distribution:
        description: "Java JDK Distribution:"
        type: string
        required: false
        default: "temurin"
      gradle-version:
        description: "Gradle Version:"
        type: string
        required: false
        default: "wrapper"

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ format('{0}-{1}-{2}-flow-node-fsts-custom-regression', github.ref_name, github.actor, github.event.inputs.panel-config) }}

jobs:
  jrs-panel:
    name: JRS Panel
    uses: ./.github/workflows/zxc-jrs-regression.yaml
    with:
      hedera-tests-enabled: true
      panel-config: ${{ github.event.inputs.panel-config }}
      ref: ${{ github.event.inputs.ref || github.ref }}
      branch-name: ${{ github.ref_name }}
      slack-results-channel: ${{ github.event.inputs.slack-results-channel }}
      slack-summary-channel: ${{ github.event.inputs.slack-summary-channel }}
      java-version: ${{ github.event.inputs.java-version || '21.0.6' }}
      java-distribution: ${{ github.event.inputs.java-distribution || 'temurin' }}
      gradle-version: ${{ github.event.inputs.gradle-version || 'wrapper' }}
      use-branch-for-slack-channel: false
      custom-job-name: "Custom"
    secrets:
      access-token: ${{ secrets.PLATFORM_GH_ACCESS_TOKEN }}
      jrs-ssh-user-name: ${{ secrets.PLATFORM_JRS_SSH_USER_NAME }}
      jrs-ssh-key-file: ${{ secrets.PLATFORM_JRS_SSH_KEY_FILE }}
      gcp-project-number: ${{ secrets.PLATFORM_GCP_PROJECT_NUMBER }}
      gcp-sa-key-contents: ${{ secrets.PLATFORM_GCP_KEY_FILE }}
      slack-api-token: ${{ secrets.PLATFORM_SLACK_API_TOKEN }}
      gradle-cache-username: ${{ secrets.GRADLE_CACHE_USERNAME }}
      gradle-cache-password: ${{ secrets.GRADLE_CACHE_PASSWORD }}
      grafana-agent-username: ${{ secrets.GRAFANA_AGENT_USERNAME }}
      grafana-agent-password: ${{ secrets.GRAFANA_AGENT_PASSWORD }}
