# SPDX-License-Identifier: Apache-2.0
name: "ZXC: TCK Regression"
on:
  workflow_call:
    inputs:
      panel-config:
        description: "The relative local path to the TCK panel configuration file:"
        required: true
        type: string
      ref:
        description: "The branch, tag or SHA to checkout:"
        required: false
        type: string
      base-branch-name:
        description: "The base branch of the pull request (if applicable):"
        required: false
        type: string
      test-path:
        description: "Path to the TCK tests to run:"
        required: false
        type: string
        default: "/"
    secrets:
      access-token:
        description: "The Github access token used to checkout the repository, submodules, and make GitHub API calls."
        required: true
      gradle-cache-username:
        description: "The username used to authenticate with the Gradle Build Cache Node."
        required: true
      gradle-cache-password:
        description: "The password used to authenticate with the Gradle Build Cache Node."
        required: true

env:
  GRADLE_CACHE_USERNAME: ${{ secrets.gradle-cache-username }}
  GRADLE_CACHE_PASSWORD: ${{ secrets.gradle-cache-password }}
  CG_EXEC: ionice -c 2 -n 2 nice -n 19
  PING_CG_EXEC: ionice -c 2 -n 2 nice -n 19

defaults:
  run:
    shell: bash
    working-directory: platform-sdk

permissions:
  id-token: write
  checks: write
  contents: read

jobs:
  tck-regression:
    name: ${{ inputs.custom-job-name || 'Standard' }}
    runs-on: hiero-network-node-linux-large
    if: ${{ !github.event.workflow_call.repository.fork }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - name: Checkout Platform Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ inputs.ref || inputs.branch-name || '' }}
          fetch-depth: 0

      - name: Checkout Regression Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          path: platform-sdk/regression
          repository: hiero-ledger/hiero-sdk-tck
          ref: ${{ inputs.ref }}
          token: ${{ secrets.access-token }}

      - name: Setup NodeJS Environment
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version: 20

      - name: Install NodeJS Dependencies
        run: |
          npm install --prefer-offline --no-audit --progress=false
          npm cache clean --force
