# SPDX-License-Identifier: Apache-2.0
name: "ZXF: [CITR] Single Day Canonical Tests (SDCT)"

on:
  workflow_dispatch:
    inputs:
      ref:
        required: true
        default: "main"
        description: "Version of hiero-consensus-node: branch, tag, commit."
        type: string
      build-tag:
        required: true
        description: "build-XXXXX tag associated with the ref input."
        type: string

defaults:
  run:
    shell: bash --noprofile --norc -euo pipefail

env:
  USERNAME: ${{ secrets.TESTING_JENKINS_API_USERNAME }}
  PASSWORD: ${{ secrets.TESTING_JENKINS_API_PASSWORD }}
  SERVER: ${{ secrets.TESTING_JENKINS_API_SERVER }}

jobs:
  canonical-test:
    name: Canonical
    runs-on: hiero-citr-linux-medium
    timeout-minutes: 60  # max one hour timeout 

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Authenticate to Google Cloud
        uses: step-security/google-github-auth@40f6deebd366f16c782d7a0ad0844e3b96a032a6 # v2.1.10
        with:
          workload_identity_provider: "projects/235822363393/locations/global/workloadIdentityPools/hedera-builds-pool/providers/hedera-builds-gh-actions"
          service_account: "hedera-artifact-builds@devops-1-254919.iam.gserviceaccount.com"

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@77e7a554d41e2ee56fc945c52dfd3f33d12def9a # v2.1.4

      - name: Verify Workflow Parameters
        id: parameters
        env:
          REF_INPUT: ${{ inputs.ref }}
          BUILD_TAG_INPUT: ${{ inputs.build-tag }}
        run: |
          set -euo pipefail

          BRANCH_NAME="${{ inputs.ref }}"
          BUILD_ARTIFACT="${{ inputs.build-tag }}"
          if [[ "${BRANCH_NAME}" = "main" ]]; then
            BRANCH_NAME_LOWER="$(echo "${BRANCH_NAME}" | tr '[:upper:]' '[:lower:]')"
            BRANCH_NAME_SAFE="$(echo "${BRANCH_NAME_LOWER}" | tr '/_' '-.')"
            TAG_COMMIT_SHA=$(git rev-list -n 1 "${BUILD_ARTIFACT}") || {
              echo "::error::Tag ${BUILD_ARTIFACT} not found"
              exit 1
            }
            TAG_COMMIT_SHORT="${TAG_COMMIT_SHA:0:8}"
            BUILD_ARTIFACT="build-${BRANCH_NAME_SAFE}-${TAG_COMMIT_SHORT}"
          fi
          echo "artifact-name=${BUILD_ARTIFACT}" >> "${GITHUB_OUTPUT}"

      - name: Check If Release Artifact Exist in Bucket
        id: check-if-exist
        run: |
          set -euo pipefail

          ARTIFACT_NAME="${{ steps.parameters.outputs.artifact-name }}"
          ARTIFACT_PATH="gs://${{ secrets.RELEASE_ARTIFACT_BUCKET_NAME }}/${ARTIFACT_NAME}.zip"
          echo "ARTIFACT_PATH=${ARTIFACT_PATH}"

          while true
          do
            gsutil -q stat "${ARTIFACT_PATH}"
            PATH_EXIST=$?
            if [ ${PATH_EXIST} -eq 0 ]; then
              break
            else
              echo "::zzz::Artifact ${ARTIFACT_NAME}.zip not ready, wait for 2 minutes."
              sleep 2m
            fi
          done
          echo "::white_check_mark::Artifact ${ARTIFACT_NAME}.zip is available."
          echo "build-version=${ARTIFACT_NAME}" >> "${GITHUB_OUTPUT}"
