# SPDX-License-Identifier: Apache-2.0
name: "ZXF: [CITR] Single Day Canonical Tests (SDCT)"

on:
  workflow_dispatch:
    inputs:
      ref:
        required: true
        default: "main"
        description: "Version of hiero-consensus-node: branch, tag, commit."
        type: string
      build-tag:
        required: true
        description: "build-XXXXX tag associated with the ref input."
        type: string

defaults:
  run:
    shell: bash -euo pipefail {0}

jobs:
  canonical-test:
    name: Canonical
    runs-on: hiero-citr-linux-medium

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          fetch-tags: true
          token: ${{ github.token }}
          persist-credentials: false

      - name: Authenticate to Google Cloud
        uses: step-security/google-github-auth@40f6deebd366f16c782d7a0ad0844e3b96a032a6 # v2.1.10
        with:
          workload_identity_provider: "projects/235822363393/locations/global/workloadIdentityPools/hedera-builds-pool/providers/hedera-builds-gh-actions"
          service_account: "hedera-artifact-builds@devops-1-254919.iam.gserviceaccount.com"
          token_format: 'access_token'
          create_credentials_file: true

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@77e7a554d41e2ee56fc945c52dfd3f33d12def9a # v2.1.4
        with:
          version: 'latest'
          install_components: "gsutil"

      - name: Install Utility Tools
        run: sudo apt update && sudo apt install -y jq curl

      - name: Verify Workflow Parameters
        id: parameters
        run: |
          set -euo pipefail

          BRANCH_NAME="${{ inputs.ref }}"
          BUILD_ARTIFACT="${{ inputs.build-tag }}"
          if [[ "${BRANCH_NAME}" = "main" ]]; then
            BRANCH_NAME_LOWER="$(echo "${BRANCH_NAME}" | tr '[:upper:]' '[:lower:]')"
            BRANCH_NAME_SAFE="$(echo "${BRANCH_NAME_LOWER}" | tr '/_' '-.')"
            TAG_COMMIT_SHA=$(git rev-list -n 1 "${BUILD_ARTIFACT}") || {
              printf '%s ❌ Error: Failed to get CRUMB from Jenkins\n' "$(date '+%Y-%m-%d %T')" >&2
              exit 1
            }
            TAG_COMMIT_SHORT="${TAG_COMMIT_SHA:0:8}"
            BUILD_ARTIFACT="build-${BRANCH_NAME_SAFE}-${TAG_COMMIT_SHORT}"
          fi
          echo "artifact-name=${BUILD_ARTIFACT}" >> "${GITHUB_OUTPUT}"

      - name: Check Artifact Availability
        id: check-if-exist
        timeout-minutes: 60  # max one hour timeout 
        run: |
          set -euo pipefail

          ARTIFACT_NAME="${{ steps.parameters.outputs.artifact-name }}"
          BUCKET_NAME="${{ secrets.RELEASE_ARTIFACT_BUCKET_NAME }}"
          if [[ -z "${ARTIFACT_NAME}" ]]; then
            printf '%s ❌ Error: Artifact name is empty\n' "$(date '+%Y-%m-%d %T')" >&2
            exit 1
          fi
          if [[ -z "${BUCKET_NAME}" ]]; then
            printf '%s ❌ Error: Bucket  name is empty\n' "$(date '+%Y-%m-%d %T')" >&2
            exit 1
          fi

          ARTIFACT_PATH="gs://${BUCKET_NAME}/${ARTIFACT_NAME}.zip"
          echo "ARTIFACT_PATH=${ARTIFACT_PATH}"

          for ((i=1;i<=30;i++)); do
              gsutil -q stat "${ARTIFACT_PATH}" && break
              echo "⏳ Artifact ${ARTIFACT_NAME}.zip not ready, wait for 2 minutes, on [$i/30] try." ; sleep 120
          done
          ((i<=30)) || {printf '%s ❌ Error: Artifact not found after 30 attempts, timed out.\n' "$(date '+%Y-%m-%d %T')"; exit 1; }

          printf '%s ✅ Artifact ${ARTIFACT_NAME}.zip is available.\n' "$(date '+%Y-%m-%d %T')" >&2
          echo "build-tag=${{ inputs.build-tag }}" >> "${GITHUB_OUTPUT}"
          echo "build-version=${ARTIFACT_NAME}" >> "${GITHUB_OUTPUT}"

      - name: Start Canonical Test
        id: start-canonical-test
        env:
          USERNAME: ${{ secrets.TESTING_JENKINS_API_USERNAME }}
          PASSWORD: ${{ secrets.TESTING_JENKINS_API_PASSWORD }}
          SERVER: ${{ secrets.TESTING_JENKINS_API_SERVER }}
          TEST_SCRIPT: ".github/workflows/support/scripts/nightly.sh"

        run: |
          bash "${{ github.workspace }}/${{ env.TEST_SCRIPT }}" \
               "${{ steps.check-if-exist.outputs.build-tag }}" \
               "${{ steps.check-if-exist.outputs.build-version }}" 

      - name: Summary
        if: always()
        run: |
          set -euo pipefail

          echo "## Workflow Summary" >> $GITHUB_STEP_SUMMARY
          echo "- **Reference**: ${{ inputs.ref }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Build Tag**: ${{ inputs.build-tag }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Artifact Name**: ${{ steps.check-if-exist.outputs.build-version }}" >> $GITHUB_STEP_SUMMARY
