# SPDX-License-Identifier: Apache-2.0
name: "CITR Single Day Performance Test"
on:
  push:
    tags:
      - 'build-*'

defaults:
  run:
    shell: bash

jobs:
  run-citr-performance-test:
    name: Run Single Day Performance Test
    runs-on: hiero-network-node-linux-large
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      # Get the `build-XXXXX' tag (latest tag) to run the performance test

      # Clone the perf analysis automation repo

      # Call the performance workflow with appropriate input version