# SPDX-License-Identifier: Apache-2.0
name: "ZZZ Test Workflow - Template Only"
on:
  workflow_dispatch:
    inputs:
      ref:
        description: "The branch, tag, or commit to checkout:"
        type: string
        required: false
        default: ""
      java-distribution:
        description: "Java JDK Distribution:"
        type: string
        required: false
        default: "temurin"
      java-version:
        description: "Java JDK Version:"
        type: string
        required: false

defaults:
  run:
    shell: bash

permissions:
  id-token: write
  contents: write
  actions: read

jobs:
  report-success:
    name: Test all Slack message templates
    runs-on: hl-cn-default-lin-sm
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Echo Input Vars
        env:
          INPUT_REF: ${{ inputs.ref }}
          JAVA_DISTRIBUTION: ${{ inputs.java-distribution }}
          JAVA_VERSION: ${{ inputs.java-version }}
        run: |
          echo "ref: ${INPUT_REF}"
          echo "java-distribution: ${{ inputs.java-distribution }}"
          echo "java-version: ${{ inputs.java-version }}"
