# SPDX-License-Identifier: Apache-2.0
name: "ZZZ Test Workflow - Template Only"
on:
  workflow_dispatch:
    inputs:
      ref:
        description: "The branch, tag, or commit to checkout:"
        type: string
        required: false
        default: ""
      java-distribution:
        description: "Java JDK Distribution:"
        type: string
        required: false
        default: "temurin"
      java-version:
        description: "Java JDK Version:"
        type: string
        required: false

defaults:
  run:
    shell: bash

permissions:
  id-token: write
  contents: write
  actions: read

jobs:
  report-success:
    name: Test all Slack message templates
    runs-on: hl-cn-default-lin-sm
    steps:
      - name: Initialize GitHub Job
        uses: pandaswhocode/initialize-github-job@bfe0b1633012cee3033c757c7095d49c360e23a6 # v1.0.1
        with:
          checkout: "true"
          checkout-ref: ${{ github.ref }}
          checkout-fetch-depth: "0"
          checkout-token: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Echo Input Vars
        env:
          INPUT_REF: ${{ inputs.ref }}
          JAVA_DISTRIBUTION: ${{ inputs.java-distribution }}
          JAVA_VERSION: ${{ inputs.java-version }}
        run: |
          echo "ref: ${INPUT_REF}"
          echo "java-distribution: ${{ inputs.java-distribution }}"
          echo "java-version: ${{ inputs.java-version }}"
